export type ShowcaseVariant = 'aurora' | 'monolith' | 'editorial' | 'verso' | 'atlas' | 'haven';
export type ShowcaseColorMode = 'light' | 'dark';

export type ShowcaseThemeTokens = {
  page: string;
  header: string;
  headerHero: string;
  headerSheet: string;
  footer: string;
  navActive: string;
  navInactive: string;
  navMonolithActive: string;
  navHover: string;
  menuItemActive: string;
  menuItemInactive: string;
  menuItemMonolith: string;
  brandFallback: string;
  brandLogoBg: string;
  themeToggleHover: string;
  sectionBorder: string;
  sectionAlt: string;
  subheading: string;
  body: string;
  muted: string;
  card: string;
  cardBorder: string;
  highlightCard: string;
  primaryBtn: string;
  secondaryBtn: string;
  heroSecondaryBtn: string;
  testimonialCard: string;
  testimonialFooter: string;
  testimonialControl: string;
  mapPinBg: string;
  galleryFrame: string;
  galleryImageBorder: string;
  amenityCell: string;
  ruleBorder: string;
  ruleText: string;
  testimonialQuote: string;
  testimonialBlock: string;
  ctaSurface: string;
  progressInactive: string;
  progressActive: string;
  marqueeBorder: string;
};

const AURORA: Record<ShowcaseColorMode, ShowcaseThemeTokens> = {
  light: {
    page: 'bg-background text-foreground',
    header:
      'border-white/50 bg-background/65 text-foreground shadow-[0_10px_40px_-18px_rgba(15,23,42,0.18)]',
    headerHero: 'border-white/35 bg-white/30 text-foreground shadow-none',
    headerSheet: 'border-border/60 bg-background/90',
    footer: 'border-border bg-background text-foreground',
    navActive: 'bg-primary/15 text-primary',
    navInactive: 'text-muted-foreground hover:text-foreground hover:bg-muted/60',
    navMonolithActive: '',
    navHover: 'hover:bg-muted',
    menuItemActive: 'bg-primary/15 text-primary',
    menuItemInactive: 'text-foreground hover:bg-muted',
    menuItemMonolith: '',
    brandFallback: 'bg-primary/15 text-primary',
    brandLogoBg: 'bg-muted/80 ring-1 ring-black/5',
    themeToggleHover: 'hover:bg-muted/70',
    sectionBorder: '',
    sectionAlt: '',
    subheading: 'text-muted-foreground',
    body: 'text-muted-foreground',
    muted: 'text-muted-foreground',
    card: 'border-border/70 bg-card/60',
    cardBorder: 'border-border/70',
    highlightCard: 'border-border/70 bg-card/40',
    primaryBtn: 'bg-primary text-primary-foreground',
    secondaryBtn: 'border-border text-foreground border',
    heroSecondaryBtn:
      'border border-white/35 bg-white/10 text-white backdrop-blur hover:bg-white/20',
    testimonialCard: 'border-border/70 bg-card/60',
    testimonialFooter: 'text-muted-foreground',
    testimonialControl: 'border-border',
    mapPinBg: 'bg-muted',
    galleryFrame: '',
    galleryImageBorder: '',
    amenityCell:
      'border-border/70 bg-card/70 hover:border-primary/40 group hover:shadow-[0_12px_30px_-18px_hsl(var(--primary)/0.55)]',
    ruleBorder: '',
    ruleText: 'text-muted-foreground',
    testimonialQuote: '',
    testimonialBlock: '',
    ctaSurface: 'from-primary/10 via-background to-background bg-gradient-to-br',
    progressInactive: 'bg-foreground/15 hover:bg-foreground/35',
    progressActive: 'bg-[hsl(var(--showcase-accent,var(--primary)))] h-10',
    marqueeBorder: 'border-border',
  },
  dark: {
    page: 'bg-slate-950 text-slate-50',
    header:
      'border-white/10 bg-slate-950/55 text-slate-50 shadow-[0_10px_40px_-18px_rgba(0,0,0,0.55)]',
    headerHero: 'border-white/15 bg-slate-950/35 text-slate-50 shadow-none',
    headerSheet: 'border-slate-800/60 bg-slate-950/92',
    footer: 'border-slate-800 bg-slate-950 text-slate-50',
    navActive: 'bg-primary/20 text-primary',
    navInactive: 'text-slate-400 hover:bg-white/5 hover:text-slate-100',
    navMonolithActive: '',
    navHover: 'hover:bg-slate-800',
    menuItemActive: 'bg-primary/20 text-primary',
    menuItemInactive: 'text-slate-100 hover:bg-slate-800',
    menuItemMonolith: '',
    brandFallback: 'bg-primary/20 text-primary',
    brandLogoBg: 'bg-slate-800 ring-1 ring-white/10',
    themeToggleHover: 'hover:bg-white/10',
    sectionBorder: '',
    sectionAlt: '',
    subheading: 'text-muted-foreground',
    body: 'text-foreground/80',
    muted: 'text-muted-foreground',
    card: 'border-slate-700/70 bg-slate-900/60',
    cardBorder: 'border-slate-700/70',
    highlightCard: 'border-slate-700 bg-slate-900/50',
    primaryBtn: 'bg-primary text-primary-foreground',
    secondaryBtn: 'border-slate-600 text-slate-100 border',
    heroSecondaryBtn:
      'border border-white/35 bg-white/10 text-white backdrop-blur hover:bg-white/20',
    testimonialCard: 'border-slate-700/70 bg-slate-900/60',
    testimonialFooter: 'text-muted-foreground',
    testimonialControl: 'border-slate-600',
    mapPinBg: 'bg-slate-800',
    galleryFrame: '',
    galleryImageBorder: '',
    amenityCell:
      'border-slate-700/70 bg-slate-900/70 hover:border-primary/40 group hover:shadow-[0_12px_30px_-18px_hsl(var(--primary)/0.55)]',
    ruleBorder: '',
    ruleText: 'text-muted-foreground',
    testimonialQuote: '',
    testimonialBlock: '',
    ctaSurface: 'from-primary/15 via-slate-950 to-slate-950 bg-gradient-to-br',
    progressInactive: 'bg-slate-600/40 hover:bg-slate-500/60',
    progressActive: 'bg-[hsl(var(--showcase-accent,var(--primary)))] h-10',
    marqueeBorder: 'border-border',
  },
};

const MONOLITH: Record<ShowcaseColorMode, ShowcaseThemeTokens> = {
  light: {
    page: 'bg-stone-100 text-neutral-900',
    header: 'border-neutral-900 bg-stone-100 text-neutral-900 shadow-none',
    headerHero: 'border-white/25 bg-transparent text-white shadow-none',
    headerSheet: 'border-neutral-200 bg-stone-100',
    footer: 'border-neutral-200 bg-stone-200/80 text-neutral-900',
    navActive: 'bg-transparent text-primary underline underline-offset-8',
    navInactive: 'text-neutral-500 hover:text-neutral-900',
    navMonolithActive: 'bg-transparent text-primary underline underline-offset-8',
    navHover: 'hover:bg-neutral-200/80',
    menuItemActive: 'bg-primary/10 text-primary',
    menuItemInactive: 'text-neutral-800 hover:bg-neutral-200/80',
    menuItemMonolith: 'rounded-none text-neutral-700 hover:bg-neutral-200/80',
    brandFallback: 'bg-neutral-900 text-neutral-50',
    brandLogoBg: 'bg-neutral-200',
    themeToggleHover: 'hover:bg-neutral-200/80',
    sectionBorder: 'border-neutral-200',
    sectionAlt: 'bg-stone-200/50',
    subheading: 'text-neutral-600',
    body: 'text-neutral-700',
    muted: 'text-neutral-500',
    card: 'border-neutral-200 bg-white/80',
    cardBorder: 'border-neutral-200',
    highlightCard: 'border-neutral-200 bg-white',
    primaryBtn: 'bg-neutral-900 text-neutral-50 hover:opacity-90',
    secondaryBtn: 'border-neutral-300 text-neutral-900 border',
    heroSecondaryBtn: 'border border-neutral-400/60 text-neutral-900 bg-white/40 backdrop-blur',
    testimonialCard: 'border border-neutral-200 bg-white/90',
    testimonialFooter: 'text-neutral-500',
    testimonialControl: 'border-neutral-300',
    mapPinBg: 'bg-stone-200',
    galleryFrame: 'border border-neutral-200',
    galleryImageBorder: 'rounded-none border-r border-neutral-200 last:border-r-0',
    amenityCell:
      'border-b border-neutral-200 @sm:odd:border-r min-h-14 px-5 py-4 uppercase tracking-[0.08em]',
    ruleBorder: 'border-b border-neutral-200',
    ruleText: 'text-neutral-600',
    testimonialQuote: 'font-instrument text-xl leading-snug @sm:text-2xl',
    testimonialBlock: 'border border-neutral-200 p-6',
    ctaSurface: 'bg-stone-200/50',
    progressInactive: '',
    progressActive: '',
    marqueeBorder: 'border-neutral-200',
  },
  dark: {
    page: 'bg-neutral-950 text-neutral-50',
    header: 'border-neutral-50 bg-neutral-950 text-neutral-50 shadow-none',
    headerHero: 'border-white/20 bg-transparent text-white shadow-none',
    headerSheet: 'border-white/10 bg-neutral-950',
    footer: 'border-border bg-neutral-950 text-foreground',
    navActive: 'bg-transparent text-primary underline underline-offset-8',
    navInactive: 'text-muted-foreground hover:text-foreground',
    navMonolithActive: 'bg-transparent text-primary underline underline-offset-8',
    navHover: 'hover:bg-white/10',
    menuItemActive: 'bg-primary/15 text-primary',
    menuItemInactive: 'text-neutral-200 hover:bg-white/10',
    menuItemMonolith: 'rounded-none text-neutral-200 hover:bg-white/10',
    brandFallback: 'bg-neutral-800 text-neutral-50',
    brandLogoBg: 'bg-neutral-800',
    themeToggleHover: 'hover:bg-white/10',
    sectionBorder: 'border-border',
    sectionAlt: 'bg-neutral-900/40',
    subheading: 'text-muted-foreground',
    body: 'text-foreground/80',
    muted: 'text-muted-foreground',
    card: 'border-white/15 bg-neutral-900/40',
    cardBorder: 'border-border',
    highlightCard: 'border-white/15 bg-neutral-900/30',
    primaryBtn: 'bg-neutral-50 text-neutral-900 hover:opacity-90',
    secondaryBtn: 'border border-border text-foreground',
    heroSecondaryBtn: 'border border-white/30 text-white',
    testimonialCard: 'border border-white/15',
    testimonialFooter: 'text-muted-foreground',
    testimonialControl: 'border-border',
    mapPinBg: 'bg-neutral-900',
    galleryFrame: 'border border-white/15',
    galleryImageBorder: 'rounded-none border-r border-white/10 last:border-r-0',
    amenityCell:
      'border-b border-border @sm:odd:border-r min-h-14 px-5 py-4 uppercase tracking-[0.08em] text-muted-foreground',
    ruleBorder: 'border-b border-border',
    ruleText: 'text-muted-foreground',
    testimonialQuote: 'font-instrument text-xl leading-snug @sm:text-2xl',
    testimonialBlock: 'border border-white/15 p-6',
    ctaSurface: '',
    progressInactive: '',
    progressActive: '',
    marqueeBorder: 'border-border',
  },
};

const EDITORIAL: Record<ShowcaseColorMode, ShowcaseThemeTokens> = {
  light: {
    page: 'bg-[#f7f3ec] text-[#1c1917]',
    header: 'border-[#1c1917]/10 bg-[#f7f3ec] text-[#1c1917] shadow-none',
    headerHero: '',
    headerSheet: 'border-[#1c1917]/15 bg-[#f7f3ec]',
    footer: 'border-[#1c1917]/10 bg-[#efe8dc] text-[#1c1917]',
    navActive: 'text-[#1c1917] underline decoration-[#1c1917]/40 underline-offset-8',
    navInactive: 'text-[#57534e] hover:text-[#1c1917]',
    navMonolithActive: '',
    navHover: 'hover:bg-[#1c1917]/5',
    menuItemActive: 'bg-[#1c1917]/10 text-[#1c1917]',
    menuItemInactive: 'text-[#1c1917] hover:bg-[#1c1917]/5',
    menuItemMonolith: '',
    brandFallback: 'bg-[#1c1917] text-[#f7f3ec]',
    brandLogoBg: 'bg-[#efe8dc] ring-1 ring-[#1c1917]/10',
    themeToggleHover: 'hover:bg-[#1c1917]/5',
    sectionBorder: '',
    sectionAlt: '',
    subheading: 'text-[#57534e]',
    body: 'text-[#44403c]',
    muted: 'text-[#78716c]',
    card: 'bg-white/70',
    cardBorder: 'border-[#1c1917]/10',
    highlightCard: 'rounded-md bg-white/70',
    primaryBtn: 'bg-[#1c1917] text-[#f7f3ec]',
    secondaryBtn: 'border border-[#1c1917]/25 text-[#1c1917]',
    heroSecondaryBtn: 'border border-[#1c1917]/25 text-[#1c1917]',
    testimonialCard: 'rounded-md bg-white p-6 shadow-[0_10px_40px_-24px_rgba(28,25,23,0.35)]',
    testimonialFooter: 'text-[#78716c]',
    testimonialControl: 'border-[#1c1917]/20',
    mapPinBg: 'bg-[#efe8dc]',
    galleryFrame: '',
    galleryImageBorder: '',
    amenityCell: 'text-[#44403c]',
    ruleBorder: '',
    ruleText: 'text-[#57534e]',
    testimonialQuote: 'font-cormorant text-2xl leading-snug text-[#1c1917] @sm:text-3xl',
    testimonialBlock: '',
    ctaSurface: 'bg-[#efe8dc]',
    progressInactive: '',
    progressActive: '',
    marqueeBorder: '',
  },
  dark: {
    page: 'bg-[#14110f] text-[#f5efe6]',
    header: 'border-[#f5efe6]/12 bg-[#14110f] text-[#f5efe6] shadow-none',
    headerHero: '',
    headerSheet: 'border-[#f5efe6]/20 bg-[#14110f]',
    footer: 'border-[#f5efe6]/10 bg-[#1c1814] text-[#f5efe6]',
    navActive: 'text-[#f5efe6] underline decoration-[#f5efe6]/40 underline-offset-8',
    navInactive: 'text-[#a8a29e] hover:text-[#f5efe6]',
    navMonolithActive: '',
    navHover: 'hover:bg-[#f5efe6]/5',
    menuItemActive: 'bg-[#f5efe6]/10 text-[#f5efe6]',
    menuItemInactive: 'text-[#f5efe6] hover:bg-[#f5efe6]/5',
    menuItemMonolith: '',
    brandFallback: 'bg-[#f5efe6] text-[#14110f]',
    brandLogoBg: 'bg-[#252019] ring-1 ring-[#f5efe6]/15',
    themeToggleHover: 'hover:bg-[#f5efe6]/5',
    sectionBorder: '',
    sectionAlt: '',
    subheading: 'text-muted-foreground',
    body: 'text-foreground/85',
    muted: 'text-muted-foreground',
    card: 'bg-[#252019]',
    cardBorder: 'border-[#f5efe6]/10',
    highlightCard: 'rounded-md bg-[#252019]',
    primaryBtn: 'bg-[#f5efe6] text-[#14110f]',
    secondaryBtn: 'border border-[#f5efe6]/25 text-[#f5efe6]',
    heroSecondaryBtn: 'border border-[#f5efe6]/25 text-[#f5efe6]',
    testimonialCard: 'rounded-md bg-[#252019] p-6 shadow-[0_10px_40px_-24px_rgba(0,0,0,0.45)]',
    testimonialFooter: 'text-[#a8a29e]',
    testimonialControl: 'border-[#f5efe6]/20',
    mapPinBg: 'bg-[#252019]',
    galleryFrame: '',
    galleryImageBorder: '',
    amenityCell: 'text-[#d6d3d1]',
    ruleBorder: '',
    ruleText: 'text-[#a8a29e]',
    testimonialQuote: 'font-cormorant text-2xl leading-snug text-[#f5efe6] @sm:text-3xl',
    testimonialBlock: '',
    ctaSurface: '',
    progressInactive: '',
    progressActive: '',
    marqueeBorder: '',
  },
};

/* ------------------------------------------------------------------ *
 * VERSO — lookbook. Chromeless gallery wall, hairline everything,
 * thin letter-spaced type, monochrome ground + one accent.
 * ------------------------------------------------------------------ */
const VERSO: Record<ShowcaseColorMode, ShowcaseThemeTokens> = {
  light: {
    page: 'bg-[#f4f4f2] text-[#111111]',
    header: 'border-[#111111] bg-[#f4f4f2] text-[#111111] shadow-none',
    headerHero: 'border-transparent bg-transparent text-white shadow-none',
    headerSheet: 'border-[#111111]/15 bg-[#f4f4f2]',
    footer: 'border-[#111111]/10 bg-[#f4f4f2] text-[#111111]',
    navActive: 'text-[#111111] underline decoration-[#111111]/50 underline-offset-[6px]',
    navInactive: 'text-[#111111]/55 hover:text-[#111111]',
    navMonolithActive: '',
    navHover: 'hover:bg-[#111111]/5',
    menuItemActive: 'bg-[#111111]/[0.06] text-[#111111]',
    menuItemInactive: 'text-[#111111]/70 hover:bg-[#111111]/5',
    menuItemMonolith: '',
    brandFallback: 'bg-[#111111] text-[#f4f4f2] rounded-none',
    brandLogoBg: 'bg-[#e6e6e2]',
    themeToggleHover: 'hover:bg-[#111111]/5',
    sectionBorder: 'border-[#111111]/10',
    sectionAlt: '',
    subheading: 'text-[#111111]/60',
    body: 'text-[#111111]/70',
    muted: 'text-[#111111]/45',
    card: 'border-[#111111]/10 bg-white',
    cardBorder: 'border-[#111111]/10',
    highlightCard: 'border-[#111111]/12 bg-transparent rounded-none',
    primaryBtn: 'bg-[#111111] text-[#f4f4f2] rounded-none',
    secondaryBtn: 'border border-[#111111]/25 text-[#111111] rounded-none',
    heroSecondaryBtn: 'border border-white/40 bg-white/5 text-white backdrop-blur',
    testimonialCard: 'border border-[#111111]/12 bg-transparent rounded-none',
    testimonialFooter: 'text-[#111111]/45',
    testimonialControl: 'border-[#111111]/25',
    mapPinBg: 'bg-[#e6e6e2]',
    galleryFrame: '',
    galleryImageBorder: 'rounded-none',
    amenityCell:
      'border-b border-[#111111]/12 py-4 text-sm uppercase tracking-[0.22em] text-[#111111]/80',
    ruleBorder: 'border-b border-[#111111]/12',
    ruleText: 'text-[#111111]/55',
    testimonialQuote: 'text-2xl @sm:text-3xl font-light leading-snug tracking-tight',
    testimonialBlock: 'border-t border-[#111111]/15 pt-6',
    ctaSurface: 'bg-[#111111] text-[#f4f4f2]',
    progressInactive: 'bg-[#111111]/15 hover:bg-[#111111]/35',
    progressActive: 'bg-[hsl(var(--showcase-accent,var(--primary)))] h-10',
    marqueeBorder: 'border-[#111111]/12',
  },
  dark: {
    page: 'bg-[#0b0b0c] text-[#f4f4f2]',
    header: 'border-[#f4f4f2] bg-[#0b0b0c] text-[#f4f4f2] shadow-none',
    headerHero: 'border-transparent bg-transparent text-white shadow-none',
    headerSheet: 'border-white/15 bg-[#0b0b0c]',
    footer: 'border-border bg-[#0b0b0c] text-foreground',
    navActive: 'text-[#f4f4f2] underline decoration-[#f4f4f2]/50 underline-offset-[6px]',
    navInactive: 'text-muted-foreground hover:text-foreground',
    navMonolithActive: '',
    navHover: 'hover:bg-white/10',
    menuItemActive: 'bg-white/10 text-[#f4f4f2]',
    menuItemInactive: 'text-muted-foreground hover:bg-[hsl(var(--showcase-border,0_0%_100%)/0.08)]',
    menuItemMonolith: '',
    brandFallback: 'bg-[#f4f4f2] text-[#0b0b0c] rounded-none',
    brandLogoBg: 'bg-white/10',
    themeToggleHover: 'hover:bg-white/10',
    sectionBorder: 'border-border',
    sectionAlt: '',
    subheading: 'text-muted-foreground',
    body: 'text-foreground/80',
    muted: 'text-muted-foreground',
    card: 'border-border bg-[hsl(var(--showcase-surface-elevated,0_0%_100%)/0.04)]',
    cardBorder: 'border-border',
    highlightCard: 'border-border bg-transparent rounded-none',
    primaryBtn: 'bg-[#f4f4f2] text-[#0b0b0c] rounded-none',
    secondaryBtn: 'border border-border text-foreground rounded-none',
    heroSecondaryBtn: 'border border-white/40 bg-white/5 text-white backdrop-blur',
    testimonialCard: 'border border-border bg-transparent rounded-none',
    testimonialFooter: 'text-muted-foreground',
    testimonialControl: 'border-border',
    mapPinBg: 'bg-white/10',
    galleryFrame: '',
    galleryImageBorder: 'rounded-none',
    amenityCell:
      'border-b border-border py-4 text-sm uppercase tracking-[0.22em] text-muted-foreground',
    ruleBorder: 'border-b border-border',
    ruleText: 'text-muted-foreground',
    testimonialQuote: 'text-2xl @sm:text-3xl font-light leading-snug tracking-tight',
    testimonialBlock: 'border-t border-border pt-6',
    ctaSurface: 'bg-[#f4f4f2] text-[#0b0b0c]',
    progressInactive: 'bg-white/15 hover:bg-white/35',
    progressActive: 'bg-[hsl(var(--showcase-accent,var(--primary)))] h-10',
    marqueeBorder: 'border-border',
  },
};

/* ------------------------------------------------------------------ *
 * ATLAS — cinematic dossier. Dark-first, atmospheric. Glass panels,
 * gradient mesh, a ticking HUD, sticky chapter headings, a map that
 * grows on scroll. Space Grotesk display + mono data.
 * ------------------------------------------------------------------ */
const ATLAS: Record<ShowcaseColorMode, ShowcaseThemeTokens> = {
  light: {
    page: 'bg-[#eef2f2] text-[#0e1516]',
    header: 'border-[#0e1516]/12 bg-white/55 text-[#0e1516] shadow-none',
    headerHero: 'border-white/20 bg-black/25 text-white shadow-none',
    headerSheet: 'border-[#0e1516]/10 bg-white/90',
    footer: 'border-[#0e1516]/10 bg-black/[0.05] text-[#0e1516]',
    navActive: 'bg-[#0e1516]/[0.08] text-[#0e1516]',
    navInactive: 'text-[#0e1516]/50 hover:bg-[#0e1516]/5 hover:text-[#0e1516]',
    navMonolithActive: '',
    navHover: 'hover:bg-[#0e1516]/5',
    menuItemActive: 'bg-[#0e1516]/[0.06] text-[#0e1516]',
    menuItemInactive: 'text-[#0e1516]/75 hover:bg-[#0e1516]/5',
    menuItemMonolith: '',
    brandFallback: 'bg-[#0e1516] text-[#eef2f2]',
    brandLogoBg: 'bg-black/[0.06] ring-1 ring-[#0e1516]/10',
    themeToggleHover: 'hover:bg-[#0e1516]/5',
    sectionBorder: 'border-[#0e1516]/10',
    /** Relative tint so Brand / Custom / From-photos palettes keep alt bands in-family (not fixed mint). */
    sectionAlt: 'bg-black/[0.04]',
    subheading: 'text-[#0e1516]/60',
    body: 'text-[#0e1516]/72',
    muted: 'text-[#0e1516]/45',
    card: 'border-[#0e1516]/10 bg-white/70',
    cardBorder: 'border-[#0e1516]/10',
    highlightCard: 'border-[#0e1516]/10 bg-white/70',
    primaryBtn: 'bg-[#0e1516] text-[#eef2f2]',
    secondaryBtn: 'border border-[#0e1516]/25 text-[#0e1516]',
    heroSecondaryBtn: 'border border-white/40 bg-white/10 text-white backdrop-blur',
    testimonialCard: 'border border-[#0e1516]/10 bg-white/70',
    testimonialFooter: 'text-[#0e1516]/45',
    testimonialControl: 'border-[#0e1516]/25',
    mapPinBg: 'bg-black/[0.06]',
    galleryFrame: '',
    galleryImageBorder: 'rounded-xl',
    amenityCell:
      'border border-[#0e1516]/10 bg-white/70 rounded-xl px-4 py-3.5 text-sm text-[#0e1516]/85',
    ruleBorder: 'border-b border-[#0e1516]/10',
    ruleText: 'text-[#0e1516]/55',
    testimonialQuote: 'text-lg @sm:text-xl leading-relaxed',
    testimonialBlock: 'rounded-2xl border border-[#0e1516]/10 bg-white/70 p-7',
    ctaSurface: 'rounded-3xl border border-[#0e1516]/12 bg-white/70',
    progressInactive: 'bg-[#0e1516]/15 hover:bg-[#0e1516]/35',
    progressActive: 'bg-[hsl(var(--showcase-accent,var(--primary)))] h-10',
    marqueeBorder: 'border-[#0e1516]/10',
  },
  dark: {
    page: 'bg-[#080c0d] text-[#dbe6e5]',
    header: 'border-white/12 bg-[#080c0d]/55 text-[#dbe6e5] shadow-none',
    headerHero: 'border-white/15 bg-black/30 text-white shadow-none',
    headerSheet: 'border-white/10 bg-[#080c0d]/95',
    footer: 'border-border bg-[#05090a] text-foreground',
    navActive: 'bg-white/[0.1] text-white',
    navInactive: 'text-muted-foreground hover:bg-[hsl(var(--showcase-border)/0.12)] hover:text-foreground',
    navMonolithActive: '',
    navHover: 'hover:bg-white/10',
    menuItemActive: 'bg-white/[0.08] text-white',
    menuItemInactive: 'text-muted-foreground hover:bg-[hsl(var(--showcase-border)/0.12)]',
    menuItemMonolith: '',
    brandFallback: 'bg-[#dbe6e5] text-[#080c0d]',
    brandLogoBg: 'bg-white/10 ring-1 ring-white/15',
    themeToggleHover: 'hover:bg-white/10',
    sectionBorder: 'border-border',
    sectionAlt: 'bg-white/[0.025]',
    subheading: 'text-muted-foreground',
    body: 'text-foreground/80',
    muted: 'text-muted-foreground',
    card: 'border-white/10 bg-white/[0.045]',
    cardBorder: 'border-border',
    highlightCard: 'border-white/10 bg-white/[0.045]',
    primaryBtn: 'bg-[#dbe6e5] text-[#080c0d]',
    secondaryBtn: 'border border-border text-foreground',
    heroSecondaryBtn: 'border border-white/35 bg-white/10 text-white backdrop-blur',
    testimonialCard: 'border border-white/10 bg-white/[0.045]',
    testimonialFooter: 'text-muted-foreground',
    testimonialControl: 'border-border',
    mapPinBg: 'bg-white/10',
    galleryFrame: '',
    galleryImageBorder: 'rounded-xl',
    amenityCell:
      'border border-border bg-[hsl(var(--showcase-surface-elevated)/0.55)] rounded-xl px-4 py-3.5 text-sm text-muted-foreground',
    ruleBorder: 'border-b border-border',
    ruleText: 'text-muted-foreground',
    testimonialQuote: 'text-lg @sm:text-xl leading-relaxed',
    testimonialBlock: 'rounded-2xl border border-white/10 bg-white/[0.045] p-7',
    ctaSurface: 'rounded-3xl border border-border bg-[hsl(var(--showcase-surface-elevated)/0.55)]',
    progressInactive: 'bg-white/15 hover:bg-white/35',
    progressActive: 'bg-[hsl(var(--showcase-accent,var(--primary)))] h-10',
    marqueeBorder: 'border-border',
  },
};

/* ------------------------------------------------------------------ *
 * HAVEN — warm hospitality. Sand paper, soft shadows, rounded
 * postcard cards, friendly serif display + humanist sans body.
 * ------------------------------------------------------------------ */
const HAVEN: Record<ShowcaseColorMode, ShowcaseThemeTokens> = {
  light: {
    page: 'bg-[#fbf7f1] text-[#2c2622]',
    header: 'border-[#2c2622]/10 bg-[#fbf7f1]/95 text-[#2c2622] backdrop-blur-md',
    headerHero: '',
    headerSheet: 'border-[#2c2622]/8 bg-[#fbf7f1]',
    footer: 'border-[#2c2622]/8 bg-black/[0.04] text-[#2c2622]',
    navActive: 'bg-[#2c2622]/[0.08] text-[#2c2622]',
    navInactive: 'text-[#2c2622]/55 hover:bg-[#2c2622]/5 hover:text-[#2c2622]',
    navMonolithActive: '',
    navHover: 'hover:bg-[#2c2622]/5',
    menuItemActive: 'bg-[#2c2622]/[0.06] text-[#2c2622]',
    menuItemInactive: 'text-[#2c2622]/75 hover:bg-[#2c2622]/5',
    menuItemMonolith: '',
    brandFallback: 'bg-[#2c2622] text-[#fbf7f1]',
    brandLogoBg: 'bg-black/[0.05] ring-1 ring-[#2c2622]/8',
    themeToggleHover: 'hover:bg-[#2c2622]/5',
    sectionBorder: 'border-[#2c2622]/8',
    /** Relative tint — follows Brand / Custom / From-photos page surface. */
    sectionAlt: 'bg-black/[0.035]',
    subheading: 'text-[#5c5248]',
    body: 'text-[#4a423b]',
    muted: 'text-[#8a7d70]',
    card: 'border-[#2c2622]/8 bg-white shadow-[0_18px_50px_-30px_rgba(44,38,34,0.35)]',
    cardBorder: 'border-[#2c2622]/8',
    highlightCard:
      'border-[#2c2622]/8 bg-white rounded-3xl shadow-[0_18px_50px_-30px_rgba(44,38,34,0.3)]',
    primaryBtn: 'bg-[#2c2622] text-[#fbf7f1] rounded-full',
    secondaryBtn: 'border border-[#2c2622]/20 text-[#2c2622] rounded-full',
    heroSecondaryBtn:
      'border border-[#2c2622]/20 bg-white/70 text-[#2c2622] backdrop-blur rounded-full',
    testimonialCard:
      'rounded-3xl border border-[#2c2622]/8 bg-white p-7 shadow-[0_20px_60px_-34px_rgba(44,38,34,0.4)]',
    testimonialFooter: 'text-[#8a7d70]',
    testimonialControl: 'border-[#2c2622]/20',
    mapPinBg: 'bg-black/[0.05]',
    galleryFrame: '',
    galleryImageBorder: 'rounded-3xl',
    amenityCell:
      'rounded-2xl border border-[#2c2622]/8 bg-white px-5 py-4 text-base text-[#4a423b] shadow-[0_14px_40px_-30px_rgba(44,38,34,0.35)]',
    ruleBorder: 'border-b border-[#2c2622]/8',
    ruleText: 'text-[#5c5248]',
    testimonialQuote: 'font-fraunces text-base leading-relaxed @sm:text-lg text-[#2c2622]',
    testimonialBlock: 'rounded-3xl border border-[#2c2622]/8 bg-white p-7',
    ctaSurface:
      'rounded-[2.5rem] bg-gradient-to-br from-[#f3ece1] via-white to-[#f6ede0] border border-[#2c2622]/8',
    progressInactive: 'bg-[#2c2622]/15 hover:bg-[#2c2622]/35',
    progressActive: 'bg-[hsl(var(--showcase-accent,var(--primary)))] h-10',
    marqueeBorder: 'border-[#2c2622]/10',
  },
  dark: {
    page: 'bg-[#1c1a17] text-[#f2ede4]',
    header: 'border-white/12 bg-[#1c1a17]/92 text-[#f2ede4] backdrop-blur-md',
    headerHero: '',
    headerSheet: 'border-white/8 bg-[#1c1a17]',
    footer: 'border-border bg-[#181513] text-foreground',
    navActive: 'bg-white/[0.1] text-[#f2ede4]',
    navInactive: 'text-muted-foreground hover:bg-[hsl(var(--showcase-border)/0.12)] hover:text-foreground',
    navMonolithActive: '',
    navHover: 'hover:bg-white/10',
    menuItemActive: 'bg-white/[0.08] text-[#f2ede4]',
    menuItemInactive: 'text-muted-foreground hover:bg-[hsl(var(--showcase-border)/0.12)]',
    menuItemMonolith: '',
    brandFallback: 'bg-[#f2ede4] text-[#1c1a17]',
    brandLogoBg: 'bg-white/10 ring-1 ring-white/15',
    themeToggleHover: 'hover:bg-white/10',
    sectionBorder: 'border-border',
    sectionAlt: 'bg-white/[0.03]',
    subheading: 'text-muted-foreground',
    body: 'text-foreground/85',
    muted: 'text-muted-foreground',
    card: 'border-white/10 bg-[#262320] shadow-[0_18px_50px_-30px_rgba(0,0,0,0.6)]',
    cardBorder: 'border-border',
    highlightCard: 'border-white/10 bg-[#262320] rounded-3xl',
    primaryBtn: 'bg-[#f2ede4] text-[#1c1a17] rounded-full',
    secondaryBtn: 'border border-border text-foreground rounded-full',
    heroSecondaryBtn:
      'border border-white/20 bg-white/10 text-[#f2ede4] backdrop-blur rounded-full',
    testimonialCard: 'rounded-3xl border border-white/10 bg-[#262320] p-7',
    testimonialFooter: 'text-muted-foreground',
    testimonialControl: 'border-border',
    mapPinBg: 'bg-white/10',
    galleryFrame: '',
    galleryImageBorder: 'rounded-3xl',
    amenityCell:
      'rounded-2xl border border-border bg-[hsl(var(--showcase-surface-elevated))] px-5 py-4 text-base text-muted-foreground',
    ruleBorder: 'border-b border-border',
    ruleText: 'text-muted-foreground',
    testimonialQuote: 'font-fraunces text-base leading-relaxed @sm:text-lg text-[#f2ede4]',
    testimonialBlock: 'rounded-3xl border border-white/10 bg-[#262320] p-7',
    ctaSurface: 'rounded-[2.5rem] border border-border bg-[hsl(var(--showcase-surface-elevated))]',
    progressInactive: 'bg-white/15 hover:bg-white/35',
    progressActive: 'bg-[hsl(var(--showcase-accent,var(--primary)))] h-10',
    marqueeBorder: 'border-border',
  },
};

const BY_VARIANT: Record<ShowcaseVariant, Record<ShowcaseColorMode, ShowcaseThemeTokens>> = {
  aurora: AURORA,
  monolith: MONOLITH,
  editorial: EDITORIAL,
  verso: VERSO,
  atlas: ATLAS,
  haven: HAVEN,
};

export function getShowcaseThemeTokens(
  variant: ShowcaseVariant,
  mode: ShowcaseColorMode
): ShowcaseThemeTokens {
  return BY_VARIANT[variant][mode];
}

export function showcaseThemeStorageKey(propertySlug: string, variant: ShowcaseVariant): string {
  return `showcase-color-mode:${propertySlug}:${variant}`;
}
