/** Minimal edge mock payloads for public marketing E2E. */

const defaultPlanFeatures = {
  automatedBookingFlow: false,
  verifiedBadgeEligible: false,
  recommendedBadgeEligible: false,
  telegramNotifications: false,
  teamManagement: { enabled: false, maxMembers: null },
  searchVisibilityTier: 'none',
  marketingPublishLimitPerGroup: 0,
  aiValidations: false,
  aiMonthlyCreditAllowance: 0,
  marketingStudio: false,
  customPages: false,
  propertyShowcase: false,
  aiDashboardAssistant: false,
  aiReceptionist: false,
  aiMarketingGeneration: false,
  aiChatAutoReply: false,
  fullyManagedByPlatform: false,
  financeReporting: false,
  maintenanceReporting: false,
  metaChatChannel: false,
  quickReplies: false,
  customTemplates: false,
  publicPagesAutosave: false,
  bookingImport: false,
  calendarSync: false,
  smartPricing: false,
  customRoles: false,
  copyPropertySettings: false,
};

export const mockPublicPricingPlansBody = {
  success: true,
  data: {
    plans: [
      {
        id: 'free',
        code: 'free',
        name: 'Free',
        tagline: null,
        sortOrder: 0,
        pricingModel: 'subscription',
        pricePhp: 0,
        discountPercent: 0,
        volumeDiscountTiers: [],
        volumeRampFloorPhp: 0,
        volumeRampAtCount: 10,
        features: defaultPlanFeatures,
        isDefault: true,
      },
      {
        id: 'starter',
        code: 'starter',
        name: 'Starter',
        tagline: null,
        sortOrder: 10,
        pricingModel: 'subscription',
        pricePhp: 399,
        discountPercent: 0,
        volumeDiscountTiers: [],
        volumeRampFloorPhp: 0,
        volumeRampAtCount: 10,
        features: defaultPlanFeatures,
        isDefault: false,
      },
      {
        id: 'pro',
        code: 'pro',
        name: 'Pro',
        tagline: null,
        sortOrder: 30,
        pricingModel: 'subscription',
        pricePhp: 1439,
        discountPercent: 0,
        volumeDiscountTiers: [],
        volumeRampFloorPhp: 0,
        volumeRampAtCount: 10,
        features: defaultPlanFeatures,
        isDefault: false,
      },
    ],
  },
};

export const mockSearchListingsBody = {
  success: true,
  data: {
    query: {
      where: '',
      checkIn: '',
      checkOut: '',
      adults: 2,
      children: 0,
      infants: 0,
      pets: 0,
      type: 'all',
      page: 1,
      pageSize: 24,
      lat: null,
      lng: null,
      focus: null,
    },
    totals: { properties: 0, developments: 0, parkings: 0, all: 0 },
    properties: [],
    developments: [],
    parkings: [],
    meta: {
      intent: 'literal',
      intentLabel: null,
      needsLocation: false,
      usedSmartFallback: false,
      conceptId: null,
    },
  },
};

export const mockPublicPropertyBody = {
  success: true,
  data: {
    id: 'property-e2e-001',
    slug: 'solea-mactan',
    name: 'Solea Mactan',
    type: 'CONDO',
    status: 'ACTIVE',
    description: 'E2E mock property',
    locationLabel: 'Lapu-Lapu, Cebu',
    address: 'Mactan',
    city: 'Lapu-Lapu',
    province: 'Cebu',
    country: 'PH',
    zipCode: null,
    latitude: null,
    longitude: null,
    mapsUrl: null,
    placeId: null,
    residenceName: 'Solea Residences',
    towerAndUnit: 'Tower 1 / 1204',
    tower: 'Tower 1',
    unitNumber: '1204',
    bedrooms: 2,
    bathrooms: 1,
    floors: 1,
    maxGuests: 4,
    maxAdults: 4,
    maxChildren: 2,
    checkInTime: '2:00 PM',
    checkOutTime: '12:00 PM',
    selfCheckIn: false,
    amenities: ['WiFi', 'Air Conditioning'],
    media: [],
    images: [],
    pricing: {
      weekdayNightlyRate: 3500,
      weekendNightlyRate: 4000,
      securityDeposit: 3000,
      petFee: 300,
      parkingRateGuest: 400,
      currency: 'PHP',
    },
    houseRules: [],
    cancellationPolicy: {
      type: 'grace_period',
      title: 'Free cancellation for 48 hours',
      description: 'Cancel within 48 hours of booking for a full refund.',
      tone: 'positive',
      showListingHighlight: true,
      shortLabel: '48h grace',
    },
    host: {
      unitName: 'Solea Mactan',
      organizationName: 'Kame Homes PH',
      organizationSlug: 'kame-homes-ph',
      organizationLogoUrl: null,
      ownerName: 'Kame Homes',
      ownerAvatarUrl: null,
      brandColor: '#0f766e',
    },
    rating: 4.9,
    reviewCount: 12,
    guestReviews: [],
    updatedAt: '2026-09-10T00:00:00.000Z',
  },
};

export const mockSearchSuggestionsBody = {
  success: true,
  data: {
    query: '',
    locations: [],
    developments: [],
    properties: [],
    parkings: [],
  },
};

export const mockPublicDevelopmentsListBody = {
  success: true,
  data: [
    {
      id: 'dev-e2e-001',
      slug: 'solea-residences',
      name: 'Solea Residences',
      developerName: 'Solea Group',
      type: 'CONDOMINIUM',
      location: 'Lapu-Lapu, Cebu',
      city: 'Lapu-Lapu',
      description: 'E2E mock development',
      coverImage: '',
      images: [] as string[],
      amenities: ['Pool'],
      propertyCount: 12,
      priceRange: { min: 3500, max: 5500 },
      propertyIds: [] as string[],
    },
  ],
  total: 1,
  page: 1,
  pageSize: 24,
  facets: {
    types: [] as string[],
    cities: [] as string[],
    price: { min: 3500, max: 5500 },
    developers: [] as string[],
  },
};

export const mockPublicPropertiesListBody = {
  success: true,
  data: [
    {
      id: 'property-e2e-001',
      slug: 'solea-mactan',
      name: 'Solea Mactan',
      type: 'CONDO',
      location: 'Lapu-Lapu, Cebu',
      price: 3500,
      rating: 4.9,
      reviews: 12,
      images: [] as string[],
      guests: 4,
      bedrooms: 2,
      bathrooms: 1,
      amenities: ['WiFi'],
    },
  ],
  total: 1,
  page: 1,
  pageSize: 24,
  facets: {
    types: [] as string[],
    price: { min: 3500, max: 3500 },
    bedrooms: [] as number[],
    amenities: [] as string[],
    developments: [] as string[],
  },
};
