#!/usr/bin/env bash
# Create git-ignored local dev env files when missing (Cloud Agent bootstrap).
# Values use deterministic Supabase CLI local defaults for the core guest-form path.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0"

UI_ENV="$ROOT/ui/.env.development"
if [[ ! -f "$UI_ENV" ]]; then
  cat > "$UI_ENV" <<EOF
# Generated by .cursor/write-env-files.sh (git-ignored).
VITE_NODE_ENV=development

VITE_SUPABASE_URL=http://127.0.0.1:54321/functions/v1
VITE_API_URL=http://127.0.0.1:54321/functions/v1
VITE_SUPABASE_ANON_KEY=${ANON_KEY}

VITE_ADMIN_ALLOWED_EMAILS=kamehome.azurenorth@gmail.com

GOOGLE_CLIENT_ID=local-placeholder.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=local-placeholder-secret
EOF
  echo "wrote $UI_ENV"
else
  echo "$UI_ENV already exists — leaving as-is"
fi

SB_ENV="$ROOT/supabase/.env.local"
if [[ ! -f "$SB_ENV" ]]; then
  cat > "$SB_ENV" <<'EOF'
# Generated by .cursor/write-env-files.sh (git-ignored).
ENVIRONMENT=development

RESEND_API_KEY=re_local_placeholder
EMAIL_TO=dev@example.com
EMAIL_REPLY_TO=dev@example.com

ADMIN_ALLOWED_EMAILS=kamehome.azurenorth@gmail.com
EOF
  echo "wrote $SB_ENV"
else
  echo "$SB_ENV already exists — leaving as-is"
fi
