#!/usr/bin/env bash
# Create the git-ignored local dev env files if they are missing.
# Values are the deterministic Supabase CLI local defaults, so they are safe to
# embed here. Real integrations (Resend, Google, Telegram, Gmail) stay as inert
# placeholders — the core guest-form flow works without them.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Local Supabase CLI anon key (fixed demo key for the default JWT secret).
ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0"

UI_ENV="$ROOT/ui/.env.development"
if [[ ! -f "$UI_ENV" ]]; then
  cat > "$UI_ENV" <<EOF
# UI / Vite dev env (git-ignored). Generated by .cursor/write-env-files.sh.
VITE_NODE_ENV=development

VITE_SUPABASE_URL=http://127.0.0.1:54321/functions/v1
VITE_API_URL=http://127.0.0.1:54321/functions/v1
VITE_SUPABASE_ANON_KEY=${ANON_KEY}

VITE_ADMIN_ALLOWED_EMAILS=kamehome.azurenorth@gmail.com

# Local Supabase Auth (Google) — inert placeholders so config.toml env() resolves.
# Real Google OAuth is only needed for admin /sign-in.
GOOGLE_CLIENT_ID=local-placeholder.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=local-placeholder-secret
EOF
  echo "wrote $UI_ENV"
else
  echo "$UI_ENV already exists — leaving as-is"
fi

SB_ENV="$ROOT/supabase/.env.local"
if [[ ! -f "$SB_ENV" ]]; then
  cat > "$SB_ENV" <<'EOF'
# Local edge-function secrets for `supabase functions serve` (git-ignored).
# Generated by .cursor/write-env-files.sh. Replace placeholders with real secrets
# to exercise email / calendar / sheet / Gmail / Telegram side effects.
ENVIRONMENT=development

RESEND_API_KEY=re_local_placeholder
EMAIL_TO=dev@example.com
EMAIL_REPLY_TO=dev@example.com

ADMIN_ALLOWED_EMAILS=kamehome.azurenorth@gmail.com
EOF
  echo "wrote $SB_ENV"
else
  echo "$SB_ENV already exists — leaving as-is"
fi
