/**
 * Guest Form Templates
 * Pre-configured form templates for common use cases
 */

import {
  type FormTemplate,
  type FormStep,
  DEFAULT_FORM_STYLING,
  DEFAULT_FORM_SETTINGS,
} from '../types';

// ============================================
// Azure Guest Advise Form Template
// ============================================

const azureSteps: FormStep[] = [
  {
    id: 'step-booking-details',
    name: 'Booking Details',
    description: 'Enter your check-in and check-out dates and guest count.',
    icon: 'Calendar',
    isOptional: false,
    order: 0,
    fields: [
      {
        id: 'field-checkin-date',
        type: 'DATE',
        label: 'Check-in Date',
        placeholder: 'Select check-in date',
        description: 'When would you like to check in?',
        required: true,
        order: 0,
        styling: { width: 'half' },
      },
      {
        id: 'field-checkout-date',
        type: 'DATE',
        label: 'Check-out Date',
        placeholder: 'Select check-out date',
        description: 'When would you like to check out?',
        required: true,
        order: 1,
        styling: { width: 'half' },
      },
      {
        id: 'field-checkin-time',
        type: 'TIME',
        label: 'Check-in Time',
        placeholder: 'Select time',
        description: 'Preferred check-in time',
        required: true,
        defaultValue: '14:00',
        order: 2,
        styling: { width: 'half' },
      },
      {
        id: 'field-checkout-time',
        type: 'TIME',
        label: 'Check-out Time',
        placeholder: 'Select time',
        description: 'Preferred check-out time',
        required: true,
        defaultValue: '11:00',
        order: 3,
        styling: { width: 'half' },
      },
      {
        id: 'field-number-adults',
        type: 'NUMBER',
        label: 'Number of Adults',
        placeholder: 'Enter number',
        description: 'How many adult guests?',
        required: true,
        defaultValue: 2,
        validation: { min: 1, max: 10 },
        order: 4,
        styling: { width: 'half' },
      },
      {
        id: 'field-number-children',
        type: 'NUMBER',
        label: 'Number of Children',
        placeholder: 'Enter number',
        description: 'How many children? (Ages 0-12)',
        required: false,
        defaultValue: 0,
        validation: { min: 0, max: 10 },
        order: 5,
        styling: { width: 'half' },
      },
    ],
  },
  {
    id: 'step-guest-info',
    name: 'Guest Information',
    description: 'Tell us about yourself and your fellow guests.',
    icon: 'User',
    isOptional: false,
    order: 1,
    fields: [
      {
        id: 'field-facebook-name',
        type: 'TEXT',
        label: 'Facebook Name',
        placeholder: 'Your Facebook profile name',
        description: 'Please provide your Facebook name for verification',
        required: true,
        order: 0,
        styling: { width: 'full' },
      },
      {
        id: 'field-primary-guest',
        type: 'TEXT',
        label: 'Primary Guest Name',
        placeholder: 'Full name as shown on ID',
        description: 'Full name of the main guest',
        required: true,
        validation: { minLength: 2, maxLength: 100 },
        order: 1,
        styling: { width: 'full' },
      },
      {
        id: 'field-email',
        type: 'EMAIL',
        label: 'Email Address',
        placeholder: 'your.email@example.com',
        description: "We'll send booking confirmation here",
        required: true,
        order: 2,
        styling: { width: 'half' },
      },
      {
        id: 'field-phone',
        type: 'PHONE',
        label: 'Phone Number',
        placeholder: '09123456789',
        description: 'Philippine mobile number (11 digits)',
        required: true,
        validation: {
          pattern: '^09\\d{9}$',
          customMessage: 'Please enter a valid 11-digit phone number starting with 09',
        },
        order: 3,
        styling: { width: 'half' },
      },
      {
        id: 'field-address',
        type: 'ADDRESS',
        label: 'Address',
        placeholder: 'City, Province',
        description: 'Your current address (City, Province)',
        required: true,
        order: 4,
        styling: { width: 'full' },
      },
      {
        id: 'field-nationality',
        type: 'SELECT',
        label: 'Nationality',
        placeholder: 'Select nationality',
        required: true,
        defaultValue: 'Filipino',
        options: [
          { id: 'opt-filipino', label: 'Filipino', value: 'Filipino' },
          { id: 'opt-american', label: 'American', value: 'American' },
          { id: 'opt-british', label: 'British', value: 'British' },
          { id: 'opt-chinese', label: 'Chinese', value: 'Chinese' },
          { id: 'opt-japanese', label: 'Japanese', value: 'Japanese' },
          { id: 'opt-korean', label: 'Korean', value: 'Korean' },
          { id: 'opt-other', label: 'Other', value: 'Other' },
        ],
        order: 5,
        styling: { width: 'half' },
      },
      {
        id: 'field-find-us',
        type: 'SELECT',
        label: 'How did you find us?',
        placeholder: 'Select option',
        required: true,
        defaultValue: 'Facebook',
        options: [
          { id: 'opt-fb', label: 'Facebook', value: 'Facebook' },
          { id: 'opt-airbnb', label: 'Airbnb', value: 'Airbnb' },
          { id: 'opt-booking', label: 'Booking.com', value: 'Booking.com' },
          { id: 'opt-referral', label: 'Friend Referral', value: 'Referral' },
          { id: 'opt-google', label: 'Google Search', value: 'Google' },
          { id: 'opt-other-source', label: 'Other', value: 'Other' },
        ],
        order: 6,
        styling: { width: 'half' },
      },
      {
        id: 'field-heading-additional',
        type: 'HEADING',
        label: 'Additional Guests',
        description: 'Please provide names of all guests for building registration',
        required: false,
        order: 7,
        styling: { width: 'full' },
      },
      {
        id: 'field-guest-2',
        type: 'TEXT',
        label: 'Guest 2 Name',
        placeholder: 'Full name (optional)',
        required: false,
        order: 8,
        styling: { width: 'half' },
      },
      {
        id: 'field-guest-3',
        type: 'TEXT',
        label: 'Guest 3 Name',
        placeholder: 'Full name (optional)',
        required: false,
        order: 9,
        styling: { width: 'half' },
      },
      {
        id: 'field-guest-4',
        type: 'TEXT',
        label: 'Guest 4 Name',
        placeholder: 'Full name (optional)',
        required: false,
        order: 10,
        styling: { width: 'half' },
      },
      {
        id: 'field-guest-5',
        type: 'TEXT',
        label: 'Guest 5 Name',
        placeholder: 'Full name (optional)',
        required: false,
        order: 11,
        styling: { width: 'half' },
      },
      {
        id: 'field-special-requests',
        type: 'TEXTAREA',
        label: 'Special Requests',
        placeholder: 'Any special requests or notes?',
        description: 'Let us know if you have any special requirements',
        required: false,
        order: 12,
        styling: { width: 'full' },
      },
    ],
  },
  {
    id: 'step-parking',
    name: 'Parking Details',
    description: 'Provide vehicle information if you need parking.',
    icon: 'Car',
    isOptional: true,
    order: 2,
    fields: [
      {
        id: 'field-need-parking',
        type: 'CHECKBOX',
        label: 'Do you need parking?',
        description: 'Check if you will be bringing a vehicle',
        required: false,
        defaultValue: false,
        order: 0,
        styling: { width: 'full' },
      },
      {
        id: 'field-plate-number',
        type: 'TEXT',
        label: 'Car Plate Number',
        placeholder: 'e.g., ABC 1234',
        required: false,
        order: 1,
        styling: { width: 'full' },
        conditional: {
          show: true,
          conditions: [{ fieldId: 'field-need-parking', operator: 'equals', value: true }],
          logic: 'AND',
        },
      },
      {
        id: 'field-car-model',
        type: 'TEXT',
        label: 'Car Brand/Model',
        placeholder: 'e.g., Toyota Fortuner',
        required: false,
        order: 2,
        styling: { width: 'half' },
        conditional: {
          show: true,
          conditions: [{ fieldId: 'field-need-parking', operator: 'equals', value: true }],
          logic: 'AND',
        },
      },
      {
        id: 'field-car-color',
        type: 'TEXT',
        label: 'Car Color',
        placeholder: 'e.g., White',
        required: false,
        order: 3,
        styling: { width: 'half' },
        conditional: {
          show: true,
          conditions: [{ fieldId: 'field-need-parking', operator: 'equals', value: true }],
          logic: 'AND',
        },
      },
    ],
  },
  {
    id: 'step-pets',
    name: 'Pet Information',
    description: "Let us know if you're bringing any pets.",
    icon: 'PawPrint',
    isOptional: true,
    order: 3,
    fields: [
      {
        id: 'field-has-pets',
        type: 'CHECKBOX',
        label: 'Will you be bringing pets?',
        description: 'Additional pet fees may apply',
        required: false,
        defaultValue: false,
        order: 0,
        styling: { width: 'full' },
      },
      {
        id: 'field-pet-name',
        type: 'TEXT',
        label: 'Pet Name',
        placeholder: "Your pet's name",
        required: false,
        order: 1,
        styling: { width: 'half' },
        conditional: {
          show: true,
          conditions: [{ fieldId: 'field-has-pets', operator: 'equals', value: true }],
          logic: 'AND',
        },
      },
      {
        id: 'field-pet-type',
        type: 'SELECT',
        label: 'Pet Type',
        placeholder: 'Select type',
        required: false,
        options: [
          { id: 'opt-dog', label: 'Dog', value: 'Dog' },
          { id: 'opt-cat', label: 'Cat', value: 'Cat' },
          { id: 'opt-other-pet', label: 'Other', value: 'Other' },
        ],
        order: 2,
        styling: { width: 'half' },
        conditional: {
          show: true,
          conditions: [{ fieldId: 'field-has-pets', operator: 'equals', value: true }],
          logic: 'AND',
        },
      },
      {
        id: 'field-pet-breed',
        type: 'TEXT',
        label: 'Pet Breed',
        placeholder: 'e.g., Golden Retriever',
        required: false,
        order: 3,
        styling: { width: 'half' },
        conditional: {
          show: true,
          conditions: [{ fieldId: 'field-has-pets', operator: 'equals', value: true }],
          logic: 'AND',
        },
      },
      {
        id: 'field-pet-age',
        type: 'TEXT',
        label: 'Pet Age',
        placeholder: 'e.g., 2 years',
        required: false,
        order: 4,
        styling: { width: 'half' },
        conditional: {
          show: true,
          conditions: [{ fieldId: 'field-has-pets', operator: 'equals', value: true }],
          logic: 'AND',
        },
      },
      {
        id: 'field-pet-vaccination',
        type: 'FILE_UPLOAD',
        label: 'Vaccination Record',
        description: "Please upload your pet's vaccination certificate",
        required: false,
        validation: { maxFileSize: 5 * 1024 * 1024, fileTypes: ['.pdf', '.jpg', '.jpeg', '.png'] },
        order: 5,
        styling: { width: 'full' },
        conditional: {
          show: true,
          conditions: [{ fieldId: 'field-has-pets', operator: 'equals', value: true }],
          logic: 'AND',
        },
      },
      {
        id: 'field-pet-image',
        type: 'IMAGE_UPLOAD',
        label: 'Pet Photo',
        description: 'Upload a recent photo of your pet',
        required: false,
        validation: { maxFileSize: 5 * 1024 * 1024, fileTypes: ['.jpg', '.jpeg', '.png'] },
        order: 6,
        styling: { width: 'full' },
        conditional: {
          show: true,
          conditions: [{ fieldId: 'field-has-pets', operator: 'equals', value: true }],
          logic: 'AND',
        },
      },
    ],
  },
  {
    id: 'step-documents',
    name: 'Required Documents',
    description: 'Please upload your valid ID and payment receipt.',
    icon: 'FileCheck',
    isOptional: false,
    order: 4,
    fields: [
      {
        id: 'field-valid-id',
        type: 'IMAGE_UPLOAD',
        label: 'Valid Government ID',
        description: 'Upload a clear photo of your valid government-issued ID',
        required: true,
        validation: { maxFileSize: 10 * 1024 * 1024, fileTypes: ['.jpg', '.jpeg', '.png', '.pdf'] },
        order: 0,
        styling: { width: 'full' },
      },
      {
        id: 'field-payment-receipt',
        type: 'IMAGE_UPLOAD',
        label: 'Payment Receipt',
        description: 'Upload a screenshot or photo of your payment receipt',
        required: true,
        validation: { maxFileSize: 10 * 1024 * 1024, fileTypes: ['.jpg', '.jpeg', '.png', '.pdf'] },
        order: 1,
        styling: { width: 'full' },
      },
    ],
  },
];

export const AZURE_GUEST_ADVISE_TEMPLATE: FormTemplate = {
  id: 'template-azure-guest-advise',
  name: 'Azure North - Guest Advise Form',
  description: 'Complete guest information form for Azure/SMDC properties',
  category: 'property_rental',
  thumbnail: '/templates/azure-form.png',
  isDefault: true,
  steps: azureSteps,
  styling: {
    ...DEFAULT_FORM_STYLING,
    primaryColor: '#0ea5e9',
    stepIndicator: {
      ...DEFAULT_FORM_STYLING.stepIndicator,
      activeColor: '#0ea5e9',
    },
  },
  settings: {
    ...DEFAULT_FORM_SETTINGS,
    submitButtonText: 'Submit Guest Form',
    successMessage:
      'Thank you! Your guest form has been submitted. We will contact you shortly with check-in instructions.',
  },
};

// ============================================
// Parking Details Only Template
// ============================================

const parkingOnlySteps: FormStep[] = [
  {
    id: 'step-parking-only',
    name: 'Parking Details',
    description: 'Provide your vehicle information for parking registration.',
    icon: 'Car',
    isOptional: false,
    order: 0,
    fields: [
      {
        id: 'field-po-guest-name',
        type: 'TEXT',
        label: 'Guest Name',
        placeholder: 'Your full name',
        description: 'Name of the guest requesting parking',
        required: true,
        order: 0,
        styling: { width: 'full' },
      },
      {
        id: 'field-po-unit',
        type: 'TEXT',
        label: 'Unit Number',
        placeholder: 'e.g., Tower 1 - 2604',
        description: 'Which unit are you staying in?',
        required: true,
        order: 1,
        styling: { width: 'half' },
      },
      {
        id: 'field-po-checkin',
        type: 'DATE',
        label: 'Check-in Date',
        required: true,
        order: 2,
        styling: { width: 'half' },
      },
      {
        id: 'field-po-divider',
        type: 'DIVIDER',
        label: '',
        required: false,
        order: 3,
        styling: { width: 'full' },
      },
      {
        id: 'field-po-heading',
        type: 'HEADING',
        label: 'Vehicle Information',
        description: 'Please provide accurate vehicle details for building security.',
        required: false,
        order: 4,
        styling: { width: 'full' },
      },
      {
        id: 'field-po-plate',
        type: 'TEXT',
        label: 'Car Plate Number',
        placeholder: 'e.g., ABC 1234',
        description: 'License plate number',
        required: true,
        order: 5,
        styling: { width: 'full' },
      },
      {
        id: 'field-po-brand',
        type: 'TEXT',
        label: 'Car Brand/Model',
        placeholder: 'e.g., Toyota Fortuner',
        required: true,
        order: 6,
        styling: { width: 'half' },
      },
      {
        id: 'field-po-color',
        type: 'TEXT',
        label: 'Car Color',
        placeholder: 'e.g., White',
        required: true,
        order: 7,
        styling: { width: 'half' },
      },
      {
        id: 'field-po-parking-duration',
        type: 'SELECT',
        label: 'Parking Duration',
        placeholder: 'Select duration',
        required: true,
        options: [
          { id: 'opt-overnight', label: 'Overnight Only', value: 'overnight' },
          { id: 'opt-full-stay', label: 'Entire Stay', value: 'full_stay' },
          { id: 'opt-specific', label: 'Specific Days', value: 'specific' },
        ],
        order: 8,
        styling: { width: 'full' },
      },
      {
        id: 'field-po-notes',
        type: 'TEXTAREA',
        label: 'Additional Notes',
        placeholder: 'Any special parking requests or notes?',
        required: false,
        order: 9,
        styling: { width: 'full' },
      },
    ],
  },
];

export const PARKING_DETAILS_TEMPLATE: FormTemplate = {
  id: 'template-parking-details',
  name: 'Parking Details Form',
  description: 'Collect vehicle information for parking registration',
  category: 'property_rental',
  thumbnail: '/templates/parking-form.png',
  steps: parkingOnlySteps,
  styling: {
    ...DEFAULT_FORM_STYLING,
    primaryColor: '#6366f1',
    stepIndicator: {
      ...DEFAULT_FORM_STYLING.stepIndicator,
      activeColor: '#6366f1',
      style: 'minimal',
    },
  },
  settings: {
    ...DEFAULT_FORM_SETTINGS,
    submitButtonText: 'Submit Parking Request',
    successMessage:
      'Your parking request has been submitted. Building admin will process your request.',
    showStepNumbers: false,
    showProgressBar: false,
  },
};

// ============================================
// Pet Information Only Template
// ============================================

const petOnlySteps: FormStep[] = [
  {
    id: 'step-pet-only',
    name: 'Pet Information',
    description: 'Register your pet for your stay. Additional pet fees may apply.',
    icon: 'PawPrint',
    isOptional: false,
    order: 0,
    fields: [
      {
        id: 'field-pet-guest-name',
        type: 'TEXT',
        label: 'Guest Name',
        placeholder: 'Your full name',
        description: 'Name of the pet owner',
        required: true,
        order: 0,
        styling: { width: 'full' },
      },
      {
        id: 'field-pet-unit',
        type: 'TEXT',
        label: 'Unit Number',
        placeholder: 'e.g., Tower 1 - 2604',
        description: 'Which unit are you staying in?',
        required: true,
        order: 1,
        styling: { width: 'half' },
      },
      {
        id: 'field-pet-checkin',
        type: 'DATE',
        label: 'Check-in Date',
        required: true,
        order: 2,
        styling: { width: 'half' },
      },
      {
        id: 'field-pet-divider',
        type: 'DIVIDER',
        label: '',
        required: false,
        order: 3,
        styling: { width: 'full' },
      },
      {
        id: 'field-pet-heading',
        type: 'HEADING',
        label: 'Pet Details',
        description: 'Please provide complete information about your pet.',
        required: false,
        order: 4,
        styling: { width: 'full' },
      },
      {
        id: 'field-pet-name',
        type: 'TEXT',
        label: 'Pet Name',
        placeholder: "Your pet's name",
        required: true,
        order: 5,
        styling: { width: 'half' },
      },
      {
        id: 'field-pet-type',
        type: 'SELECT',
        label: 'Pet Type',
        placeholder: 'Select pet type',
        required: true,
        options: [
          { id: 'opt-dog', label: 'Dog', value: 'Dog' },
          { id: 'opt-cat', label: 'Cat', value: 'Cat' },
          { id: 'opt-bird', label: 'Bird', value: 'Bird' },
          { id: 'opt-small', label: 'Small Pet (hamster, rabbit, etc.)', value: 'Small' },
          { id: 'opt-other', label: 'Other', value: 'Other' },
        ],
        order: 6,
        styling: { width: 'half' },
      },
      {
        id: 'field-pet-breed',
        type: 'TEXT',
        label: 'Breed',
        placeholder: 'e.g., Golden Retriever, Persian Cat',
        required: true,
        order: 7,
        styling: { width: 'half' },
      },
      {
        id: 'field-pet-age',
        type: 'TEXT',
        label: 'Age',
        placeholder: 'e.g., 2 years, 6 months',
        required: true,
        order: 8,
        styling: { width: 'half' },
      },
      {
        id: 'field-pet-weight',
        type: 'TEXT',
        label: 'Weight (approximate)',
        placeholder: 'e.g., 10 kg',
        required: false,
        order: 9,
        styling: { width: 'half' },
      },
      {
        id: 'field-pet-neutered',
        type: 'SELECT',
        label: 'Spayed/Neutered?',
        placeholder: 'Select',
        required: true,
        options: [
          { id: 'opt-yes', label: 'Yes', value: 'yes' },
          { id: 'opt-no', label: 'No', value: 'no' },
        ],
        order: 10,
        styling: { width: 'half' },
      },
      {
        id: 'field-pet-vaccination-date',
        type: 'DATE',
        label: 'Last Vaccination Date',
        description: 'Date of most recent vaccination',
        required: true,
        order: 11,
        styling: { width: 'full' },
      },
      {
        id: 'field-pet-vaccination-cert',
        type: 'FILE_UPLOAD',
        label: 'Vaccination Certificate',
        description: "Upload your pet's vaccination record (PDF, JPG, PNG)",
        required: true,
        validation: { maxFileSize: 5 * 1024 * 1024, fileTypes: ['.pdf', '.jpg', '.jpeg', '.png'] },
        order: 12,
        styling: { width: 'full' },
      },
      {
        id: 'field-pet-photo',
        type: 'IMAGE_UPLOAD',
        label: 'Pet Photo',
        description: 'Upload a recent photo of your pet',
        required: true,
        validation: { maxFileSize: 5 * 1024 * 1024, fileTypes: ['.jpg', '.jpeg', '.png'] },
        order: 13,
        styling: { width: 'full' },
      },
      {
        id: 'field-pet-special-needs',
        type: 'TEXTAREA',
        label: 'Special Needs or Notes',
        placeholder: 'Any special care requirements, allergies, or behavioral notes?',
        required: false,
        order: 14,
        styling: { width: 'full' },
      },
      {
        id: 'field-pet-agreement',
        type: 'CHECKBOX',
        label:
          'I agree to be responsible for my pet during my stay and will cover any damages caused.',
        required: true,
        order: 15,
        styling: { width: 'full' },
      },
    ],
  },
];

export const PET_INFORMATION_TEMPLATE: FormTemplate = {
  id: 'template-pet-information',
  name: 'Pet Information Form',
  description: 'Register pets and upload vaccination records',
  category: 'property_rental',
  thumbnail: '/templates/pet-form.png',
  steps: petOnlySteps,
  styling: {
    ...DEFAULT_FORM_STYLING,
    primaryColor: '#f59e0b',
    stepIndicator: {
      ...DEFAULT_FORM_STYLING.stepIndicator,
      activeColor: '#f59e0b',
      style: 'minimal',
    },
  },
  settings: {
    ...DEFAULT_FORM_SETTINGS,
    submitButtonText: 'Submit Pet Registration',
    successMessage:
      "Your pet registration has been submitted. We'll review it and get back to you shortly.",
    showStepNumbers: false,
    showProgressBar: false,
  },
};

// ============================================
// Simple Booking Form Template
// ============================================

const simpleSteps: FormStep[] = [
  {
    id: 'step-simple-booking',
    name: 'Booking Information',
    description: 'Enter your booking and contact details.',
    icon: 'Calendar',
    isOptional: false,
    order: 0,
    fields: [
      {
        id: 'field-simple-name',
        type: 'TEXT',
        label: 'Full Name',
        placeholder: 'Your full name',
        required: true,
        order: 0,
        styling: { width: 'full' },
      },
      {
        id: 'field-simple-email',
        type: 'EMAIL',
        label: 'Email',
        placeholder: 'your@email.com',
        required: true,
        order: 1,
        styling: { width: 'half' },
      },
      {
        id: 'field-simple-phone',
        type: 'PHONE',
        label: 'Phone Number',
        placeholder: '09123456789',
        required: true,
        order: 2,
        styling: { width: 'half' },
      },
      {
        id: 'field-simple-checkin',
        type: 'DATE',
        label: 'Check-in Date',
        required: true,
        order: 3,
        styling: { width: 'half' },
      },
      {
        id: 'field-simple-checkout',
        type: 'DATE',
        label: 'Check-out Date',
        required: true,
        order: 4,
        styling: { width: 'half' },
      },
      {
        id: 'field-simple-guests',
        type: 'NUMBER',
        label: 'Number of Guests',
        defaultValue: 2,
        validation: { min: 1, max: 10 },
        required: true,
        order: 5,
        styling: { width: 'half' },
      },
      {
        id: 'field-simple-message',
        type: 'TEXTAREA',
        label: 'Message',
        placeholder: 'Any additional notes or requests',
        required: false,
        order: 6,
        styling: { width: 'full' },
      },
    ],
  },
];

export const SIMPLE_BOOKING_TEMPLATE: FormTemplate = {
  id: 'template-simple-booking',
  name: 'Simple Booking Form',
  description: 'A minimal form for quick guest bookings',
  category: 'hospitality',
  thumbnail: '/templates/simple-form.png',
  steps: simpleSteps,
  styling: {
    ...DEFAULT_FORM_STYLING,
    primaryColor: '#10b981',
    stepIndicator: {
      ...DEFAULT_FORM_STYLING.stepIndicator,
      activeColor: '#10b981',
      style: 'minimal',
    },
  },
  settings: {
    ...DEFAULT_FORM_SETTINGS,
    showStepNumbers: false,
    showProgressBar: false,
  },
};

// ============================================
// Contact & Inquiry Template
// ============================================

const contactSteps: FormStep[] = [
  {
    id: 'step-contact',
    name: 'Contact Information',
    description: 'Tell us how to reach you.',
    icon: 'Mail',
    isOptional: false,
    order: 0,
    fields: [
      {
        id: 'field-contact-name',
        type: 'TEXT',
        label: 'Name',
        placeholder: 'Your name',
        required: true,
        order: 0,
        styling: { width: 'half' },
      },
      {
        id: 'field-contact-email',
        type: 'EMAIL',
        label: 'Email',
        placeholder: 'your@email.com',
        required: true,
        order: 1,
        styling: { width: 'half' },
      },
      {
        id: 'field-contact-phone',
        type: 'PHONE',
        label: 'Phone (Optional)',
        placeholder: '09123456789',
        required: false,
        order: 2,
        styling: { width: 'full' },
      },
    ],
  },
  {
    id: 'step-inquiry',
    name: 'Your Inquiry',
    description: 'What would you like to know?',
    icon: 'MessageSquare',
    isOptional: false,
    order: 1,
    fields: [
      {
        id: 'field-inquiry-type',
        type: 'SELECT',
        label: 'Inquiry Type',
        required: true,
        options: [
          { id: 'opt-avail', label: 'Check Availability', value: 'availability' },
          { id: 'opt-pricing', label: 'Pricing Questions', value: 'pricing' },
          { id: 'opt-amenities', label: 'Amenities & Features', value: 'amenities' },
          { id: 'opt-booking-inquiry', label: 'Booking Inquiry', value: 'booking' },
          { id: 'opt-other-inquiry', label: 'Other', value: 'other' },
        ],
        order: 0,
        styling: { width: 'full' },
      },
      {
        id: 'field-inquiry-message',
        type: 'TEXTAREA',
        label: 'Message',
        placeholder: 'Please describe your inquiry...',
        required: true,
        validation: { minLength: 10, maxLength: 1000 },
        order: 1,
        styling: { width: 'full' },
      },
      {
        id: 'field-preferred-dates',
        type: 'TEXT',
        label: 'Preferred Dates (if applicable)',
        placeholder: 'e.g., March 15-20, 2024',
        required: false,
        order: 2,
        styling: { width: 'full' },
      },
    ],
  },
];

export const CONTACT_INQUIRY_TEMPLATE: FormTemplate = {
  id: 'template-contact-inquiry',
  name: 'Contact & Inquiry Form',
  description: 'General inquiry form for potential guests',
  category: 'hospitality',
  thumbnail: '/templates/contact-form.png',
  steps: contactSteps,
  styling: {
    ...DEFAULT_FORM_STYLING,
    primaryColor: '#8b5cf6',
    stepIndicator: {
      ...DEFAULT_FORM_STYLING.stepIndicator,
      activeColor: '#8b5cf6',
      style: 'progress',
    },
  },
  settings: {
    ...DEFAULT_FORM_SETTINGS,
    submitButtonText: 'Send Inquiry',
    successMessage: 'Thank you for your inquiry! We will get back to you within 24 hours.',
  },
};

// ============================================
// Guest Feedback Template
// ============================================

const feedbackSteps: FormStep[] = [
  {
    id: 'step-feedback-info',
    name: 'Your Stay',
    description: 'Tell us about your recent stay.',
    icon: 'Calendar',
    isOptional: false,
    order: 0,
    fields: [
      {
        id: 'field-fb-name',
        type: 'TEXT',
        label: 'Your Name',
        placeholder: 'Full name',
        required: true,
        order: 0,
        styling: { width: 'half' },
      },
      {
        id: 'field-fb-email',
        type: 'EMAIL',
        label: 'Email Address',
        placeholder: 'your@email.com',
        description: 'We may follow up on your feedback',
        required: true,
        order: 1,
        styling: { width: 'half' },
      },
      {
        id: 'field-fb-checkin',
        type: 'DATE',
        label: 'Check-in Date',
        required: true,
        order: 2,
        styling: { width: 'half' },
      },
      {
        id: 'field-fb-checkout',
        type: 'DATE',
        label: 'Check-out Date',
        required: true,
        order: 3,
        styling: { width: 'half' },
      },
      {
        id: 'field-fb-unit',
        type: 'TEXT',
        label: 'Unit/Room',
        placeholder: 'e.g., Tower 1 - 2604',
        required: false,
        order: 4,
        styling: { width: 'full' },
      },
    ],
  },
  {
    id: 'step-feedback-rating',
    name: 'Rating & Feedback',
    description: 'Share your experience with us.',
    icon: 'Star',
    isOptional: false,
    order: 1,
    fields: [
      {
        id: 'field-fb-heading-overall',
        type: 'HEADING',
        label: 'Overall Experience',
        description: 'How would you rate your stay?',
        required: false,
        order: 0,
        styling: { width: 'full' },
      },
      {
        id: 'field-fb-overall-rating',
        type: 'RADIO',
        label: 'Overall Rating',
        required: true,
        options: [
          { id: 'opt-5', label: '⭐⭐⭐⭐⭐ Excellent', value: '5' },
          { id: 'opt-4', label: '⭐⭐⭐⭐ Very Good', value: '4' },
          { id: 'opt-3', label: '⭐⭐⭐ Good', value: '3' },
          { id: 'opt-2', label: '⭐⭐ Fair', value: '2' },
          { id: 'opt-1', label: '⭐ Poor', value: '1' },
        ],
        order: 1,
        styling: { width: 'full' },
      },
      {
        id: 'field-fb-divider-1',
        type: 'DIVIDER',
        label: '',
        required: false,
        order: 2,
        styling: { width: 'full' },
      },
      {
        id: 'field-fb-heading-specific',
        type: 'HEADING',
        label: 'Specific Ratings',
        description: 'Rate different aspects of your stay.',
        required: false,
        order: 3,
        styling: { width: 'full' },
      },
      {
        id: 'field-fb-cleanliness',
        type: 'SELECT',
        label: 'Cleanliness',
        placeholder: 'Select rating',
        required: true,
        options: [
          { id: 'opt-c5', label: '5 - Spotless', value: '5' },
          { id: 'opt-c4', label: '4 - Very Clean', value: '4' },
          { id: 'opt-c3', label: '3 - Clean', value: '3' },
          { id: 'opt-c2', label: '2 - Could be Better', value: '2' },
          { id: 'opt-c1', label: '1 - Needs Improvement', value: '1' },
        ],
        order: 4,
        styling: { width: 'half' },
      },
      {
        id: 'field-fb-communication',
        type: 'SELECT',
        label: 'Communication',
        placeholder: 'Select rating',
        required: true,
        options: [
          { id: 'opt-cm5', label: '5 - Excellent', value: '5' },
          { id: 'opt-cm4', label: '4 - Very Good', value: '4' },
          { id: 'opt-cm3', label: '3 - Good', value: '3' },
          { id: 'opt-cm2', label: '2 - Fair', value: '2' },
          { id: 'opt-cm1', label: '1 - Poor', value: '1' },
        ],
        order: 5,
        styling: { width: 'half' },
      },
      {
        id: 'field-fb-checkin-exp',
        type: 'SELECT',
        label: 'Check-in Experience',
        placeholder: 'Select rating',
        required: true,
        options: [
          { id: 'opt-ch5', label: '5 - Seamless', value: '5' },
          { id: 'opt-ch4', label: '4 - Very Smooth', value: '4' },
          { id: 'opt-ch3', label: '3 - Okay', value: '3' },
          { id: 'opt-ch2', label: '2 - Some Issues', value: '2' },
          { id: 'opt-ch1', label: '1 - Difficult', value: '1' },
        ],
        order: 6,
        styling: { width: 'half' },
      },
      {
        id: 'field-fb-amenities',
        type: 'SELECT',
        label: 'Amenities & Facilities',
        placeholder: 'Select rating',
        required: true,
        options: [
          { id: 'opt-a5', label: '5 - Exceeded Expectations', value: '5' },
          { id: 'opt-a4', label: '4 - Met Expectations', value: '4' },
          { id: 'opt-a3', label: '3 - Adequate', value: '3' },
          { id: 'opt-a2', label: '2 - Below Expectations', value: '2' },
          { id: 'opt-a1', label: '1 - Disappointing', value: '1' },
        ],
        order: 7,
        styling: { width: 'half' },
      },
      {
        id: 'field-fb-location',
        type: 'SELECT',
        label: 'Location',
        placeholder: 'Select rating',
        required: true,
        options: [
          { id: 'opt-l5', label: '5 - Perfect Location', value: '5' },
          { id: 'opt-l4', label: '4 - Great Location', value: '4' },
          { id: 'opt-l3', label: '3 - Good Location', value: '3' },
          { id: 'opt-l2', label: '2 - Okay Location', value: '2' },
          { id: 'opt-l1', label: '1 - Poor Location', value: '1' },
        ],
        order: 8,
        styling: { width: 'half' },
      },
      {
        id: 'field-fb-value',
        type: 'SELECT',
        label: 'Value for Money',
        placeholder: 'Select rating',
        required: true,
        options: [
          { id: 'opt-v5', label: '5 - Excellent Value', value: '5' },
          { id: 'opt-v4', label: '4 - Good Value', value: '4' },
          { id: 'opt-v3', label: '3 - Fair Value', value: '3' },
          { id: 'opt-v2', label: '2 - Overpriced', value: '2' },
          { id: 'opt-v1', label: '1 - Not Worth It', value: '1' },
        ],
        order: 9,
        styling: { width: 'half' },
      },
      {
        id: 'field-fb-divider-2',
        type: 'DIVIDER',
        label: '',
        required: false,
        order: 10,
        styling: { width: 'full' },
      },
      {
        id: 'field-fb-liked',
        type: 'TEXTAREA',
        label: 'What did you like most?',
        placeholder: 'Tell us what made your stay special...',
        required: false,
        order: 11,
        styling: { width: 'full' },
      },
      {
        id: 'field-fb-improve',
        type: 'TEXTAREA',
        label: 'What could we improve?',
        placeholder: 'Your suggestions help us get better...',
        required: false,
        order: 12,
        styling: { width: 'full' },
      },
      {
        id: 'field-fb-recommend',
        type: 'RADIO',
        label: 'Would you recommend us to friends or family?',
        required: true,
        options: [
          { id: 'opt-yes', label: 'Yes, definitely!', value: 'yes' },
          { id: 'opt-maybe', label: 'Maybe', value: 'maybe' },
          { id: 'opt-no', label: 'Probably not', value: 'no' },
        ],
        order: 13,
        styling: { width: 'full' },
      },
      {
        id: 'field-fb-return',
        type: 'RADIO',
        label: 'Would you stay with us again?',
        required: true,
        options: [
          { id: 'opt-r-yes', label: 'Yes, absolutely!', value: 'yes' },
          { id: 'opt-r-maybe', label: 'Perhaps', value: 'maybe' },
          { id: 'opt-r-no', label: 'Unlikely', value: 'no' },
        ],
        order: 14,
        styling: { width: 'full' },
      },
      {
        id: 'field-fb-testimonial',
        type: 'CHECKBOX',
        label: 'You may use my feedback as a testimonial on your website/social media',
        required: false,
        order: 15,
        styling: { width: 'full' },
      },
    ],
  },
];

export const GUEST_FEEDBACK_TEMPLATE: FormTemplate = {
  id: 'template-guest-feedback',
  name: 'Guest Feedback Form',
  description: 'Collect guest reviews and ratings after their stay',
  category: 'hospitality',
  thumbnail: '/templates/feedback-form.png',
  steps: feedbackSteps,
  styling: {
    ...DEFAULT_FORM_STYLING,
    primaryColor: '#ec4899',
    stepIndicator: {
      ...DEFAULT_FORM_STYLING.stepIndicator,
      activeColor: '#ec4899',
      style: 'progress',
    },
  },
  settings: {
    ...DEFAULT_FORM_SETTINGS,
    submitButtonText: 'Submit Feedback',
    successMessage:
      'Thank you for your feedback! We truly appreciate you taking the time to share your experience with us. 💖',
  },
};

// ============================================
// Blank Template
// ============================================

const blankSteps: FormStep[] = [
  {
    id: 'step-blank',
    name: 'Step 1',
    description: '',
    isOptional: false,
    order: 0,
    fields: [],
  },
];

export const BLANK_TEMPLATE: FormTemplate = {
  id: 'template-blank',
  name: 'Blank Form',
  description: 'Start from scratch with an empty form',
  category: 'custom',
  thumbnail: '/templates/blank-form.png',
  steps: blankSteps,
  styling: DEFAULT_FORM_STYLING,
  settings: DEFAULT_FORM_SETTINGS,
};

// ============================================
// Export All Templates
// ============================================

export const FORM_TEMPLATES: FormTemplate[] = [
  // Property Rental
  AZURE_GUEST_ADVISE_TEMPLATE,
  PARKING_DETAILS_TEMPLATE,
  PET_INFORMATION_TEMPLATE,
  // Hospitality
  SIMPLE_BOOKING_TEMPLATE,
  CONTACT_INQUIRY_TEMPLATE,
  GUEST_FEEDBACK_TEMPLATE,
  // Custom
  BLANK_TEMPLATE,
];

export function getTemplateById(id: string): FormTemplate | undefined {
  return FORM_TEMPLATES.find((t) => t.id === id);
}

export function getTemplatesByCategory(category: FormTemplate['category']): FormTemplate[] {
  return FORM_TEMPLATES.filter((t) => t.category === category);
}
