#!/usr/bin/env bash
# GitHub Actions / CI entrypoint for Supabase deploy (multi-tenant dev track).
# Usage: ./scripts/deploy/ci-deploy.sh dev [-- db-only | --functions-only | ...]
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
# shellcheck source=scripts/deploy/ci-deploy-lib.sh
source "$ROOT/scripts/deploy/ci-deploy-lib.sh"

usage() {
  cat <<'EOF'
Usage: ./scripts/deploy/ci-deploy.sh dev [deploy-supabase-dev.sh options...]

Environment (required for dev):
  SUPABASE_ACCESS_TOKEN     Supabase personal access token
  SUPABASE_PROJECT_REF      Target project (MULTI_TENANT_DEV, e.g. fwor…)
  LEGACY_PROD_PROJECT_REF   Deny-list ref (LEGACY, e.g. zftt…) — required in CI
  DEPLOY_CONFIRM=dev        Non-interactive confirm
  CI=1                      Set automatically in GitHub Actions

Optional passthrough flags after `--`:
  --db-only, --functions-only, --include-all

Always passes --allow-multi-tenancy for dev CD (multi-tenant branch).

Example (GitHub Actions):
  env:
    CI: "1"
    DEPLOY_CONFIRM: dev
    SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
    LEGACY_PROD_PROJECT_REF: ${{ secrets.LEGACY_PROD_PROJECT_REF }}
  run: ./scripts/deploy/ci-deploy.sh dev
EOF
}

TARGET="${1:-}"
shift || true

if [[ "$TARGET" != "dev" ]]; then
  echo "ERROR: only 'dev' is implemented in v1 CI (got '${TARGET:-}')." >&2
  usage >&2
  exit 1
fi

if [[ "${1:-}" == "--" ]]; then
  shift
fi

ci_deploy_require_env SUPABASE_ACCESS_TOKEN
ci_deploy_require_env SUPABASE_PROJECT_REF
ci_deploy_require_env LEGACY_PROD_PROJECT_REF

export CI="${CI:-1}"
export DEPLOY_CONFIRM="${DEPLOY_CONFIRM:-dev}"

ci_deploy_assert_not_legacy_ref "$SUPABASE_PROJECT_REF" "$LEGACY_PROD_PROJECT_REF"

echo "CI deploy target: $(ci_deploy_mask_ref "$SUPABASE_PROJECT_REF")"
echo "Legacy deny-list: $(ci_deploy_mask_ref "$LEGACY_PROD_PROJECT_REF")"

# Ephemeral env for deploy/backup classification on CI runners (no committed secrets).
ENV_FILE="$ROOT/supabase/.env.dev.local"
cat >"$ENV_FILE" <<EOF
# Generated by ci-deploy.sh — ephemeral on CI runners only
DEV_PROJECT_REF=${SUPABASE_PROJECT_REF}
PROD_PROJECT_REF=${LEGACY_PROD_PROJECT_REF}
DEV_SUPABASE_URL=https://${SUPABASE_PROJECT_REF}.supabase.co
DEV_SERVICE_ROLE_KEY=ci-placeholder-not-used-for-db-push
EOF

export SUPABASE_ACCESS_TOKEN

exec "$ROOT/scripts/deploy/deploy-supabase-dev.sh" --allow-multi-tenancy "$@"
