import {
  createDefaultStyles,
  type CalendarStyles,
} from '@/features/dashboard/marketing/components/calendar-builder/types';

export type CalendarPresetCategory = {
  label: string;
  presets: Array<{
    value: string;
    label: string;
    description: string;
    color: string;
    secondary?: string;
  }>;
};

/** Sidebar picker — categories and preset cards. Soft, pastel-led design system. */
export const CALENDAR_PRESET_CATEGORIES: CalendarPresetCategory[] = [
  {
    label: 'Sweet Social',
    presets: [
      {
        value: 'social-availability',
        label: 'Bubble Pop',
        description: 'Circle-dot days · centered title · lavender pastel',
        color: '#a48ee0',
        secondary: '#f3edfd',
      },
      {
        value: 'sunrise-select',
        label: 'Sunny Widget',
        description: 'Butter widget card · price pill · corner day mark',
        color: '#f2a154',
        secondary: '#fff3da',
      },
    ],
  },
  {
    label: 'Cute Type',
    presets: [
      {
        value: 'desk-type',
        label: 'Desk Buddy',
        description: 'Periwinkle header band · centered giant type',
        color: '#8fa8dc',
        secondary: '#eef3fc',
      },
      {
        value: 'magazine-grid',
        label: 'Zine Soft',
        description: 'Pastel editorial hairlines · left masthead',
        color: '#c98aa0',
        secondary: '#fdf6ef',
      },
    ],
  },
  {
    label: 'Playful Pattern',
    presets: [
      {
        value: 'bauhaus-geo',
        label: 'Confetti Blocks',
        description: 'Pastel color blocks · sticker shadow · rounded',
        color: '#8fb8e8',
        secondary: '#fef0d6',
      },
      {
        value: 'memphis-print',
        label: 'Sprinkle Print',
        description: 'Dot confetti · coral dashes · bubblegum badge',
        color: '#f2879e',
        secondary: '#eaf3fb',
      },
    ],
  },
  {
    label: 'Botanical',
    presets: [
      {
        value: 'boho-soft',
        label: 'Boho Breeze',
        description: 'Borderless · only special days get a pastel dot',
        color: '#e3a488',
        secondary: '#fbf1e8',
      },
      {
        value: 'garden-glow',
        label: 'Garden Bloom',
        description: 'Lush mint blobs · every day in soft color',
        color: '#7fc79e',
        secondary: '#e8f9ee',
      },
    ],
  },
  {
    label: 'Photo Story',
    presets: [
      {
        value: 'property-hero',
        label: 'Sunlit Stay',
        description: 'Blush photo wash · frosted glass · heart corner',
        color: '#ef9c85',
        secondary: '#fdece5',
      },
      {
        value: 'cabin-retreat',
        label: 'Cabin Glow',
        description: 'Warm photo overlay · chunky rounded · nav pills',
        color: '#d9a184',
        secondary: '#fbeee3',
      },
    ],
  },
  {
    label: 'Twilight',
    presets: [
      {
        value: 'velvet-guest',
        label: 'Dreamy Dusk',
        description: 'Soft lilac dusk gradient · guest-name spans',
        color: '#b48bd9',
        secondary: '#f3e8fb',
      },
      {
        value: 'gold-foil',
        label: 'Rose Gold',
        description: 'Blush plaque · rose-gold double border',
        color: '#e0a8a0',
        secondary: '#fbe9ec',
      },
    ],
  },
  {
    label: 'Paper & Ink',
    presets: [
      {
        value: 'ring-bloom',
        label: 'Ring Bloom',
        description: 'Thin gold rings on every day · elegant circles',
        color: '#c9a86a',
        secondary: '#fdf6ee',
      },
      {
        value: 'petal-note',
        label: 'Petal Note',
        description: 'No cell fills — states read purely by ink color',
        color: '#e8a186',
        secondary: '#fbe0d9',
      },
    ],
  },
];

export const CALENDAR_DESIGNER_PRESET_IDS = CALENDAR_PRESET_CATEGORIES.flatMap((c) =>
  c.presets.map((p) => p.value)
);

const d = createDefaultStyles;

/** Designer preset style partials — merged in calendarBuilderStore resolveCalendarPresetStyles. */
export const CALENDAR_PRESET_STYLES: Record<string, Partial<CalendarStyles>> = {
  // ── Bubble Pop — circular day dots, centered header, lavender pastel ──
  'social-availability': {
    container: {
      ...d().container,
      background: { type: 'solid', color: '#fffaf6' },
      border: { width: 0, style: 'none', color: 'transparent', radius: 32 },
      shadow: {
        enabled: true,
        x: 0,
        y: 20,
        blur: 56,
        spread: -16,
        color: 'rgba(164, 142, 224, 0.28)',
        inset: false,
      },
      padding: { top: 44, right: 38, bottom: 34, left: 38 },
      maxWidth: 820,
      borderRadius: 32,
    },
    header: {
      ...d().header,
      padding: { top: 0, right: 0, bottom: 24, left: 0 },
      title: { ...d().header.title, alignment: 'center' },
      propertyName: {
        ...d().header.propertyName,
        color: '#a48ee0',
        font: {
          ...d().header.propertyName.font,
          family: 'Poppins',
          weight: 600,
          size: 25,
          letterSpacing: 2.5,
          textTransform: 'uppercase',
        },
      },
      monthYear: {
        ...d().header.monthYear,
        format: 'MMMM YYYY',
        color: '#5b3f8f',
        font: {
          ...d().header.monthYear.font,
          family: 'Fraunces',
          weight: 600,
          size: 40,
          lineHeight: 1.15,
        },
      },
      subtitle: {
        ...d().header.subtitle,
        show: true,
        text: 'Available dates',
        color: '#b8a8d9',
        font: {
          ...d().header.subtitle.font,
          family: 'Nunito Sans',
          weight: 500,
          size: 15,
          lineHeight: 1.4,
        },
      },
    },
    dayNames: {
      ...d().dayNames,
      color: '#c1b3e0',
      font: {
        ...d().dayNames.font,
        family: 'Poppins',
        weight: 600,
        size: 13,
        letterSpacing: 1,
        textTransform: 'uppercase',
      },
      padding: { top: 10, right: 4, bottom: 10, left: 4 },
      border: { width: 0, style: 'none', color: 'transparent', radius: 0 },
      format: 'narrow',
    },
    grid: { ...d().grid, gap: 10 },
    cell: {
      ...d().cell,
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
      border: { width: 0, style: 'none', color: 'transparent', radius: 999 },
      borderRadius: 999,
      background: { type: 'solid', color: 'transparent' },
      dayNumber: {
        ...d().cell.dayNumber,
        font: { ...d().cell.dayNumber.font, family: 'Poppins', weight: 500, size: 18 },
        color: '#8874b8',
        position: 'center',
      },
    },
    today: {
      ...d().today,
      background: { type: 'solid', color: '#ffe1e8' },
      border: { width: 3, style: 'solid', color: '#ff8fa8', radius: 999 },
      dayNumberColor: '#c23d63',
      indicator: { show: false, type: 'ring', color: '#ff8fa8', size: 4 },
    },
    booked: {
      ...d().booked,
      background: { type: 'solid', color: '#f1ecf7' },
      dayNumberColor: '#c7bce0',
      border: { width: 0, style: 'none', color: 'transparent', radius: 999 },
      text: { ...d().booked.text, show: false },
      pattern: { show: true, type: 'dots', color: '#d9cdec', opacity: 0.7, size: 5 },
    },
    available: {
      ...d().available,
      background: { type: 'solid', color: '#ded1fb' },
      dayNumberColor: '#5b3f8f',
      border: { width: 0, style: 'none', color: 'transparent', radius: 999 },
    },
    blocked: {
      ...d().blocked,
      background: { type: 'solid', color: '#fafafa' },
      dayNumberColor: '#e3dcf0',
      border: { width: 0, style: 'none', color: 'transparent', radius: 999 },
      pattern: { show: false, type: 'none', color: '#e5e7eb', opacity: 0 },
      text: { ...d().blocked.text, show: false },
    },
    legend: {
      ...d().legend,
      show: true,
      position: 'bottom',
      background: { type: 'solid', color: 'transparent' },
      padding: { top: 22, right: 0, bottom: 0, left: 0 },
      border: { width: 1, style: 'solid', color: '#f3edfd', radius: 0 },
      borderRadius: 0,
      item: {
        ...d().legend.item,
        gap: 22,
        labelFont: { ...d().legend.item.labelFont, family: 'Nunito Sans', weight: 600, size: 13 },
        labelColor: '#a89bc4',
        indicatorSize: 13,
        indicatorBorderRadius: 999,
      },
    },
  },

  // ── Sunny Widget — butter-peach date-picker card, corner day mark ──
  'sunrise-select': {
    container: {
      ...d().container,
      background: { type: 'solid', color: '#fff8e7' },
      border: { width: 1.5, style: 'solid', color: '#ffe4b8', radius: 22 },
      shadow: {
        enabled: true,
        x: 0,
        y: 14,
        blur: 36,
        spread: -10,
        color: 'rgba(242, 161, 84, 0.22)',
        inset: false,
      },
      padding: { top: 34, right: 30, bottom: 30, left: 30 },
      maxWidth: 780,
      borderRadius: 22,
    },
    header: {
      ...d().header,
      title: { ...d().header.title, alignment: 'left' },
      propertyName: {
        ...d().header.propertyName,
        color: '#f2a154',
        font: {
          ...d().header.propertyName.font,
          family: 'Figtree',
          weight: 700,
          size: 25,
          letterSpacing: 1.5,
        },
      },
      monthYear: {
        ...d().header.monthYear,
        color: '#5c4326',
        font: {
          ...d().header.monthYear.font,
          family: 'Figtree',
          weight: 700,
          size: 40,
          lineHeight: 1.1,
        },
      },
    },
    dayNames: {
      ...d().dayNames,
      color: '#c99a5b',
      font: {
        ...d().dayNames.font,
        family: 'Figtree',
        weight: 700,
        size: 12,
        letterSpacing: 0.5,
        textTransform: 'uppercase',
      },
    },
    grid: { ...d().grid, gap: 6 },
    cell: {
      ...d().cell,
      border: { width: 0, style: 'none', color: 'transparent', radius: 14 },
      borderRadius: 14,
      background: { type: 'solid', color: '#ffffff' },
      dayNumber: {
        ...d().cell.dayNumber,
        font: { ...d().cell.dayNumber.font, family: 'Figtree', weight: 600, size: 23 },
        color: '#8a6a3f',
        position: 'top-right',
      },
    },
    today: {
      ...d().today,
      background: { type: 'solid', color: '#ffffff' },
      border: { width: 2, style: 'solid', color: '#f2a154', radius: 14 },
      dayNumberColor: '#e57e2b',
      indicator: { show: true, type: 'underline', color: '#f2a154', size: 5 },
    },
    booked: {
      ...d().booked,
      background: { type: 'solid', color: '#ffe0ba' },
      dayNumberColor: '#a9702f',
      text: {
        ...d().booked.text,
        show: true,
        content: 'BOOKED',
        color: '#c98a44',
        font: { ...d().booked.text.font, family: 'Figtree', weight: 700, size: 13 },
      },
    },
    available: {
      ...d().available,
      background: { type: 'solid', color: '#ffffff' },
      dayNumberColor: '#8a6a3f',
      price: {
        ...d().available.price,
        show: true,
        color: '#f2a154',
        font: { ...d().available.price.font, family: 'Figtree', weight: 700, size: 12 },
        position: 'bottom',
      },
    },
    blocked: {
      ...d().blocked,
      background: { type: 'solid', color: '#fef3da' },
      dayNumberColor: '#e0b878',
      text: { ...d().blocked.text, show: true, content: 'N/A', color: '#e0b878' },
    },
  },

  // ── Desk Buddy — periwinkle poster header band, centered giant type ──
  'desk-type': {
    container: {
      ...d().container,
      background: { type: 'solid', color: '#fffaf5' },
      border: { width: 0, style: 'none', color: 'transparent', radius: 26 },
      shadow: {
        enabled: true,
        x: 0,
        y: 18,
        blur: 48,
        spread: -14,
        color: 'rgba(143, 168, 220, 0.28)',
        inset: false,
      },
      padding: { top: 0, right: 30, bottom: 30, left: 30 },
      maxWidth: 820,
      borderRadius: 26,
    },
    header: {
      ...d().header,
      background: { type: 'solid', color: '#b7cdf0' },
      padding: { top: 30, right: 26, bottom: 30, left: 26 },
      border: { width: 0, style: 'none', color: 'transparent', radius: 0 },
      title: { ...d().header.title, alignment: 'center' },
      propertyName: {
        ...d().header.propertyName,
        color: '#33456e',
        font: {
          ...d().header.propertyName.font,
          family: 'Nunito Sans',
          weight: 700,
          size: 25,
          letterSpacing: 3,
          textTransform: 'uppercase',
        },
      },
      monthYear: {
        ...d().header.monthYear,
        format: 'MMMM YYYY',
        color: '#22315a',
        font: {
          ...d().header.monthYear.font,
          family: 'Poppins',
          weight: 700,
          size: 40,
          lineHeight: 1.05,
          letterSpacing: -0.5,
        },
      },
      navigation: {
        show: false,
        buttonBackground: '#ffffff',
        buttonColor: '#33456e',
        buttonBorder: { width: 0, style: 'none', color: 'transparent', radius: 999 },
        buttonSize: 32,
        hoverBackground: '#eef3fc',
        hoverColor: '#33456e',
      },
    },
    dayNames: {
      ...d().dayNames,
      color: '#6f86b8',
      font: {
        ...d().dayNames.font,
        family: 'Nunito Sans',
        weight: 700,
        size: 13,
        letterSpacing: 1,
        textTransform: 'uppercase',
      },
      padding: { top: 18, right: 0, bottom: 10, left: 0 },
    },
    grid: { ...d().grid, gap: 4, padding: { top: 6, right: 0, bottom: 0, left: 0 } },
    cell: {
      ...d().cell,
      border: { width: 0, style: 'none', color: 'transparent', radius: 18 },
      borderRadius: 18,
      background: { type: 'solid', color: '#eef3fc' },
      dayNumber: {
        ...d().cell.dayNumber,
        font: { ...d().cell.dayNumber.font, family: 'Poppins', weight: 600, size: 20 },
        color: '#4a5b82',
        position: 'top-center',
      },
    },
    today: {
      ...d().today,
      background: { type: 'solid', color: '#eef3fc' },
      border: { width: 3, style: 'solid', color: '#9fd8bd', radius: 18 },
      dayNumberColor: '#4f9c76',
      indicator: { show: false, type: 'ring', color: '#9fd8bd', size: 5 },
    },
    booked: {
      ...d().booked,
      background: { type: 'solid', color: '#8fa8dc' },
      dayNumberColor: '#ffffff',
      border: { width: 0, style: 'none', color: 'transparent', radius: 18 },
      text: {
        ...d().booked.text,
        show: true,
        content: '♥',
        color: '#ffffff',
        font: { ...d().booked.text.font, size: 13 },
        position: 'bottom',
      },
    },
    available: {
      ...d().available,
      background: { type: 'solid', color: '#eef3fc' },
      dayNumberColor: '#4a5b82',
      border: { width: 0, style: 'none', color: 'transparent', radius: 18 },
    },
    blocked: {
      ...d().blocked,
      background: { type: 'solid', color: '#f2f0f6' },
      dayNumberColor: '#c7cfe0',
      border: { width: 0, style: 'none', color: 'transparent', radius: 18 },
      pattern: { show: true, type: 'diagonal', color: '#dbe1ef', opacity: 0.7 },
    },
  },

  // ── Zine Soft — pastel editorial hairlines, left masthead ──
  'magazine-grid': {
    container: {
      ...d().container,
      background: { type: 'solid', color: '#fffaf0' },
      border: { width: 1.5, style: 'solid', color: '#e8c9d1', radius: 12 },
      shadow: {
        enabled: true,
        x: 0,
        y: 10,
        blur: 28,
        spread: -12,
        color: 'rgba(201, 138, 160, 0.16)',
        inset: false,
      },
      padding: { top: 36, right: 34, bottom: 34, left: 34 },
      maxWidth: 860,
      borderRadius: 12,
    },
    header: {
      ...d().header,
      padding: { top: 0, right: 0, bottom: 22, left: 0 },
      border: { width: 0, style: 'solid', color: '#e8c9d1', radius: 0 },
      title: { ...d().header.title, alignment: 'left' },
      propertyName: {
        ...d().header.propertyName,
        color: '#c98aa0',
        font: {
          ...d().header.propertyName.font,
          family: 'Jost',
          size: 25,
          letterSpacing: 3,
          textTransform: 'uppercase',
        },
      },
      monthYear: {
        ...d().header.monthYear,
        color: '#8a5a72',
        font: {
          ...d().header.monthYear.font,
          family: 'Fraunces',
          weight: 600,
          size: 40,
          lineHeight: 1.08,
        },
      },
    },
    dayNames: {
      ...d().dayNames,
      color: '#c98aa0',
      font: { ...d().dayNames.font, family: 'Jost', weight: 500, size: 12, letterSpacing: 2 },
      border: { width: 0, style: 'solid', color: '#e8c9d1', radius: 0 },
      padding: { top: 0, right: 4, bottom: 10, left: 4 },
      alignment: 'left',
    },
    grid: { ...d().grid, gap: 15 },
    cell: {
      ...d().cell,
      border: { width: 1, style: 'solid', color: '#f1dee3', radius: 20 },
      borderRadius: 8,
      background: { type: 'solid', color: '#fffaf0' },
      dayNumber: {
        ...d().cell.dayNumber,
        font: { ...d().cell.dayNumber.font, family: 'Jost', size: 22 },
        color: '#8a6a75',
      },
    },
    today: {
      ...d().today,
      background: { type: 'solid', color: 'transparent' },
      border: { width: 2, style: 'solid', color: '#c98aa0', radius: 20 },
      dayNumberColor: '#8a5a72',
      indicator: { show: true, type: 'dot', color: '#c98aa0', size: 4 },
    },
    booked: {
      ...d().booked,
      background: { type: 'solid', color: '#f6d9de' },
      dayNumberColor: '#a5647a',
      border: { width: 1, style: 'solid', color: '#f1dee3', radius: 20 },
      text: {
        ...d().booked.text,
        show: true,
        content: 'BOOKED',
        color: '#a5647a',
        font: { ...d().booked.text.font, family: 'Jost', size: 11, letterSpacing: 1 },
      },
    },
    available: {
      ...d().available,
      background: { type: 'solid', color: '#fffaf0' },
      border: { width: 1, style: 'solid', color: '#f1dee3', radius: 20 },
    },
    blocked: {
      ...d().blocked,
      background: { type: 'solid', color: '#fbf2ed' },
      dayNumberColor: '#d9bcc5',
      border: { width: 1, style: 'solid', color: '#f1dee3', radius: 20 },
      text: {
        ...d().blocked.text,
        show: true,
        content: 'CLOSED',
        color: '#d9bcc5',
        font: {
          ...d().blocked.text.font,
          family: 'Jost',
          size: 9,
          letterSpacing: 1,
          textTransform: 'uppercase',
        },
      },
      pattern: { show: true, type: 'diagonal', color: '#e8c9d1', opacity: 0.6 },
    },
    legend: {
      ...d().legend,
      show: true,
      background: { type: 'solid', color: 'transparent' },
      border: { width: 0, style: 'solid', color: '#e8c9d1', radius: 0 },
      borderRadius: 0,
      item: {
        ...d().legend.item,
        labelFont: {
          ...d().legend.item.labelFont,
          family: 'Jost',
          size: 11,
          letterSpacing: 1,
          textTransform: 'uppercase',
        },
        labelColor: '#a5647a',
        indicatorBorderRadius: 3,
      },
    },
  },

  // ── Confetti Blocks — pastel color blocks, sticker shadow ──
  'bauhaus-geo': {
    container: {
      ...d().container,
      background: { type: 'solid', color: '#fefbf6' },
      border: { width: 3, style: 'solid', color: '#c9b8e8', radius: 20 },
      shadow: {
        enabled: true,
        x: 7,
        y: 7,
        blur: 0,
        spread: 0,
        color: 'rgba(201, 184, 232, 0.55)',
        inset: false,
      },
      padding: { top: 32, right: 30, bottom: 30, left: 30 },
      maxWidth: 800,
      borderRadius: 20,
    },
    header: {
      ...d().header,
      padding: { top: 0, right: 0, bottom: 18, left: 0 },
      title: { ...d().header.title, alignment: 'left' },
      propertyName: {
        ...d().header.propertyName,
        color: '#8fa8dc',
        font: {
          ...d().header.propertyName.font,
          family: 'Space Grotesk',
          weight: 700,
          size: 25,
          letterSpacing: 1,
        },
      },
      monthYear: {
        ...d().header.monthYear,
        color: '#5b4b8a',
        font: {
          ...d().header.monthYear.font,
          family: 'Space Grotesk',
          weight: 700,
          size: 40,
          lineHeight: 1.05,
        },
      },
    },
    dayNames: {
      ...d().dayNames,
      background: { type: 'solid', color: '#c9b8e8' },
      color: '#ffffff',
      font: {
        ...d().dayNames.font,
        family: 'Space Grotesk',
        weight: 700,
        size: 12,
        letterSpacing: 0.5,
      },
      padding: { top: 9, right: 4, bottom: 9, left: 4 },
      border: { width: 0, style: 'none', color: 'transparent', radius: 10 },
    },
    grid: { ...d().grid, gap: 7 },
    cell: {
      ...d().cell,
      border: { width: 2.5, style: 'solid', color: '#e3d9f5', radius: 16 },
      borderRadius: 16,
      background: { type: 'solid', color: '#ffffff' },
      dayNumber: {
        ...d().cell.dayNumber,
        font: { ...d().cell.dayNumber.font, family: 'Space Grotesk', weight: 700, size: 19 },
        color: '#5b4b8a',
      },
    },
    today: {
      ...d().today,
      background: { type: 'solid', color: '#fef0d6' },
      border: { width: 2.5, style: 'solid', color: '#f2c869', radius: 16 },
      dayNumberColor: '#8a6a1f',
      indicator: { show: true, type: 'badge', color: '#f2c869', size: 4 },
    },
    booked: {
      ...d().booked,
      background: { type: 'solid', color: '#f2879e' },
      dayNumberColor: '#ffffff',
      border: { width: 2.5, style: 'solid', color: '#f2879e', radius: 16 },
      icon: {
        show: true,
        type: 'icon',
        value: 'heart',
        size: 18,
        color: '#ffffff',
        position: 'center',
        opacity: 0.95,
      },
      text: { ...d().booked.text, show: false },
    },
    available: {
      ...d().available,
      background: { type: 'solid', color: '#ffffff' },
      border: { width: 2.5, style: 'solid', color: '#e3d9f5', radius: 16 },
    },
    blocked: {
      ...d().blocked,
      background: { type: 'solid', color: '#f3f0f9' },
      dayNumberColor: '#c9b8e8',
      border: { width: 2.5, style: 'solid', color: '#e3d9f5', radius: 16 },
      text: { ...d().blocked.text, show: true, content: '—', color: '#c9b8e8' },
      pattern: { show: false, type: 'none', color: '#c9b8e8', opacity: 0 },
    },
  },

  // ── Sprinkle Print — pastel dot confetti, coral dashes, bubblegum badge ──
  'memphis-print': {
    container: {
      ...d().container,
      background: {
        type: 'pattern',
        color: '#fef9f9',
        pattern: { type: 'dots', color: '#f2879e', size: 9, opacity: 0.12 },
      },
      border: { width: 2, style: 'dashed', color: '#f2879e', radius: 22 },
      shadow: {
        enabled: true,
        x: 8,
        y: 8,
        blur: 0,
        spread: 0,
        color: 'rgba(143, 184, 232, 0.4)',
        inset: false,
      },
      padding: { top: 32, right: 30, bottom: 30, left: 30 },
      maxWidth: 800,
      borderRadius: 22,
    },
    header: {
      ...d().header,
      title: { ...d().header.title, alignment: 'left' },
      propertyName: {
        ...d().header.propertyName,
        color: '#8fb8e8',
        font: { ...d().header.propertyName.font, family: 'Space Grotesk', weight: 700, size: 25 },
      },
      monthYear: {
        ...d().header.monthYear,
        color: '#c9506d',
        font: {
          ...d().header.monthYear.font,
          family: 'Space Grotesk',
          weight: 700,
          size: 40,
          lineHeight: 1,
        },
      },
    },
    dayNames: {
      ...d().dayNames,
      background: { type: 'solid', color: '#fce4ea' },
      color: '#c9506d',
      font: { ...d().dayNames.font, family: 'Space Grotesk', weight: 700, size: 12 },
      border: { width: 0, style: 'none', color: 'transparent', radius: 10 },
    },
    grid: { ...d().grid, gap: 8 },
    cell: {
      ...d().cell,
      border: { width: 1.5, style: 'solid', color: '#fbdde5', radius: 14 },
      borderRadius: 14,
      dayNumber: {
        ...d().cell.dayNumber,
        font: { ...d().cell.dayNumber.font, family: 'Space Grotesk', weight: 700, size: 19 },
        color: '#c9506d',
        position: 'top-right',
      },
    },
    today: {
      ...d().today,
      background: { type: 'solid', color: '#eaf3fb' },
      border: { width: 1.5, style: 'solid', color: '#8fb8e8', radius: 14 },
      dayNumberColor: '#5081b8',
      indicator: { show: true, type: 'badge', color: '#f2879e', size: 5 },
    },
    booked: {
      ...d().booked,
      background: { type: 'solid', color: '#f2879e' },
      dayNumberColor: '#ffffff',
      border: { width: 1.5, style: 'solid', color: '#f2879e', radius: 14 },
      pattern: { show: true, type: 'dots', color: '#ffffff', opacity: 0.3, size: 5 },
    },
    available: {
      ...d().available,
      background: { type: 'solid', color: '#ffffff' },
      border: { width: 1.5, style: 'solid', color: '#fbdde5', radius: 14 },
    },
    blocked: {
      ...d().blocked,
      background: { type: 'solid', color: '#fef3da' },
      dayNumberColor: '#dbb877',
      border: { width: 1.5, style: 'solid', color: '#fbdde5', radius: 14 },
      pattern: { show: true, type: 'diagonal', color: '#f2c869', opacity: 0.35 },
    },
  },

  // ── Boho Breeze — borderless, only special days get a pastel dot ──
  'boho-soft': {
    container: {
      ...d().container,
      background: {
        type: 'gradient',
        color: '#fbf1e8',
        gradient: {
          type: 'linear',
          angle: 165,
          stops: [
            { color: '#fdf8f4', position: 0 },
            { color: '#fbf1e8', position: 100 },
          ],
        },
      },
      border: { width: 0, style: 'none', color: 'transparent', radius: 30 },
      shadow: {
        enabled: true,
        x: 0,
        y: 16,
        blur: 44,
        spread: -14,
        color: 'rgba(227, 164, 136, 0.2)',
        inset: false,
      },
      padding: { top: 40, right: 36, bottom: 34, left: 36 },
      maxWidth: 800,
      borderRadius: 30,
    },
    header: {
      ...d().header,
      title: { ...d().header.title, alignment: 'center' },
      propertyName: {
        ...d().header.propertyName,
        color: '#e3a488',
        font: {
          ...d().header.propertyName.font,
          family: 'Cormorant Garamond',
          size: 25,
          letterSpacing: 2,
        },
      },
      monthYear: {
        ...d().header.monthYear,
        format: 'MMMM YYYY',
        color: '#c17a56',
        font: {
          ...d().header.monthYear.font,
          family: 'Fraunces',
          weight: 500,
          size: 40,
          lineHeight: 1.1,
        },
      },
    },
    dayNames: {
      ...d().dayNames,
      color: '#c4a68f',
      font: {
        ...d().dayNames.font,
        family: 'Cormorant Garamond',
        weight: 600,
        size: 25,
        letterSpacing: 1,
      },
      border: { width: 0, style: 'none', color: 'transparent', radius: 0 },
      format: 'narrow',
    },
    grid: { ...d().grid, gap: 20 },
    cell: {
      ...d().cell,
      border: { width: 0, style: 'none', color: 'transparent', radius: 999 },
      borderRadius: 999,
      background: { type: 'solid', color: 'transparent' },
      dayNumber: {
        ...d().cell.dayNumber,
        font: { ...d().cell.dayNumber.font, family: 'Cormorant Garamond', weight: 600, size: 33 },
        color: '#8a6a54',
        position: 'center',
      },
    },
    today: {
      ...d().today,
      background: { type: 'solid', color: '#e8927a' },
      border: { width: 0, style: 'none', color: 'transparent', radius: 999 },
      dayNumberColor: '#ffffff',
      indicator: { show: false, type: 'dot', color: '#e8927a', size: 4 },
    },
    booked: {
      ...d().booked,
      background: { type: 'solid', color: '#f0b9a4' },
      dayNumberColor: '#ffffff',
      border: { width: 0, style: 'none', color: 'transparent', radius: 999 },
      text: { ...d().booked.text, show: false },
    },
    available: {
      ...d().available,
      background: { type: 'solid', color: 'transparent' },
      dayNumberColor: '#a6876f',
      border: { width: 0, style: 'none', color: 'transparent', radius: 999 },
    },
    blocked: {
      ...d().blocked,
      background: { type: 'solid', color: 'transparent' },
      dayNumberColor: '#d9c3ae',
      border: { width: 0, style: 'none', color: 'transparent', radius: 999 },
      text: { ...d().blocked.text, show: false },
      pattern: { show: false, type: 'none', color: '#e3a488', opacity: 0 },
    },
    watermark: {
      ...d().watermark,
      show: true,
      text: 'Your brand',
      color: '#e3a488',
      opacity: 0.3,
      position: 'bottom-right',
      size: 11,
      font: {
        ...d().watermark.font,
        family: 'Cormorant Garamond',
        weight: 500,
        size: 11,
        lineHeight: 1,
        letterSpacing: 2,
        textTransform: 'uppercase',
      },
    },
  },

  // ── Garden Bloom — lush mint blobs, every day in soft color ──
  'garden-glow': {
    container: {
      ...d().container,
      background: {
        type: 'gradient',
        color: '#eafaf1',
        gradient: {
          type: 'linear',
          angle: 150,
          stops: [
            { color: '#eafaf1', position: 0 },
            { color: '#d5f2e3', position: 60 },
            { color: '#fef3da', position: 100 },
          ],
        },
      },
      border: { width: 0, style: 'none', color: 'transparent', radius: 30 },
      shadow: {
        enabled: true,
        x: 0,
        y: 16,
        blur: 44,
        spread: -14,
        color: 'rgba(127, 199, 158, 0.22)',
        inset: false,
      },
      padding: { top: 36, right: 34, bottom: 34, left: 34 },
      maxWidth: 800,
      borderRadius: 30,
    },
    header: {
      ...d().header,
      title: { ...d().header.title, alignment: 'left' },
      propertyName: {
        ...d().header.propertyName,
        color: '#5fa77e',
        font: {
          ...d().header.propertyName.font,
          family: 'DM Sans',
          weight: 600,
          size: 25,
          letterSpacing: 2,
        },
      },
      monthYear: {
        ...d().header.monthYear,
        color: '#3d7a5a',
        font: { ...d().header.monthYear.font, family: 'Fraunces', weight: 600, size: 40 },
      },
    },
    dayNames: {
      ...d().dayNames,
      color: '#7fc79e',
      font: { ...d().dayNames.font, family: 'DM Sans', weight: 600, size: 12, letterSpacing: 1.5 },
    },
    grid: { ...d().grid, gap: 9 },
    cell: {
      ...d().cell,
      border: { width: 0, style: 'none', color: 'transparent', radius: 26 },
      borderRadius: 26,
      background: { type: 'solid', color: 'rgba(255,255,255,0.7)' },
      dayNumber: {
        ...d().cell.dayNumber,
        font: { ...d().cell.dayNumber.font, family: 'DM Sans', size: 20 },
        color: '#3d7a5a',
      },
    },
    today: {
      ...d().today,
      background: { type: 'solid', color: '#ffcf9e' },
      border: { width: 0, style: 'none', color: 'transparent', radius: 26 },
      dayNumberColor: '#8a5a1f',
      indicator: { show: true, type: 'dot', color: '#ffffff', size: 5 },
    },
    booked: {
      ...d().booked,
      background: { type: 'solid', color: '#a8d8ba' },
      dayNumberColor: '#2e5c42',
      border: { width: 0, style: 'none', color: 'transparent', radius: 26 },
      text: {
        ...d().booked.text,
        show: true,
        content: 'BOOKED',
        color: 'rgba(46,92,66,0.85)',
        font: { ...d().booked.text.font, family: 'DM Sans', size: 15 },
      },
    },
    available: {
      ...d().available,
      background: { type: 'solid', color: 'rgba(255,255,255,0.7)' },
      price: {
        ...d().available.price,
        show: true,
        color: '#5fa77e',
        font: { ...d().available.price.font, family: 'DM Sans', weight: 700, size: 12 },
      },
    },
    blocked: {
      ...d().blocked,
      background: { type: 'solid', color: 'rgba(213, 242, 227, 0.55)' },
      dayNumberColor: '#9fd4b8',
      border: { width: 0, style: 'none', color: 'transparent', radius: 26 },
      pattern: { show: true, type: 'diagonal', color: '#a8d8ba', opacity: 0.4 },
    },
    legend: {
      ...d().legend,
      show: true,
      background: { type: 'solid', color: 'transparent' },
      item: {
        ...d().legend.item,
        labelFont: { ...d().legend.item.labelFont, family: 'DM Sans', size: 13 },
        labelColor: '#5fa77e',
        indicatorBorderRadius: 10,
      },
    },
  },

  // ── Sunlit Stay — blush photo wash, frosted glass, heart corner ──
  'property-hero': {
    container: {
      ...d().container,
      background: {
        type: 'image',
        color: '#fffaf6',
        imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80',
        imageSize: 'cover',
        imagePosition: 'center',
        overlay: 'rgba(255, 247, 240, 0.87)',
        opacity: 1,
      },
      border: { width: 0, style: 'none', color: 'transparent', radius: 24 },
      shadow: {
        enabled: true,
        x: 0,
        y: 14,
        blur: 44,
        spread: -10,
        color: 'rgba(239, 156, 133, 0.28)',
        inset: false,
      },
      padding: { top: 34, right: 32, bottom: 32, left: 32 },
      maxWidth: 800,
      borderRadius: 24,
    },
    header: {
      ...d().header,
      title: { ...d().header.title, alignment: 'left' },
      propertyName: {
        ...d().header.propertyName,
        color: '#ef9c85',
        font: {
          ...d().header.propertyName.font,
          family: 'Plus Jakarta Sans',
          weight: 700,
          size: 25,
          letterSpacing: 2,
        },
      },
      monthYear: {
        ...d().header.monthYear,
        color: '#8a4f3e',
        font: { ...d().header.monthYear.font, family: 'Plus Jakarta Sans', weight: 700, size: 40 },
      },
    },
    dayNames: {
      ...d().dayNames,
      background: { type: 'solid', color: 'rgba(255,255,255,0.7)' },
      color: '#c17357',
      font: { ...d().dayNames.font, family: 'Plus Jakarta Sans', weight: 600, size: 12 },
      border: { width: 0, style: 'none', color: 'transparent', radius: 10 },
    },
    grid: { ...d().grid, gap: 8 },
    cell: {
      ...d().cell,
      border: { width: 0, style: 'none', color: 'transparent', radius: 16 },
      borderRadius: 16,
      background: { type: 'solid', color: 'rgba(255,255,255,0.75)' },
      dayNumber: {
        ...d().cell.dayNumber,
        font: { ...d().cell.dayNumber.font, family: 'Plus Jakarta Sans', weight: 600, size: 18 },
        color: '#8a4f3e',
      },
    },
    today: {
      ...d().today,
      background: { type: 'solid', color: '#ef9c85' },
      border: { width: 0, style: 'none', color: 'transparent', radius: 16 },
      dayNumberColor: '#ffffff',
      indicator: { show: true, type: 'dot', color: '#ffffff', size: 5 },
    },
    booked: {
      ...d().booked,
      background: { type: 'solid', color: 'rgba(255,255,255,0.85)' },
      dayNumberColor: '#c17357',
      border: { width: 1, style: 'solid', color: 'rgba(239,156,133,0.4)', radius: 16 },
      icon: {
        show: true,
        type: 'icon',
        value: 'heart',
        size: 13,
        color: '#ef9c85',
        position: 'top-right',
        opacity: 0.9,
      },
      text: { ...d().booked.text, show: false },
    },
    available: {
      ...d().available,
      background: { type: 'solid', color: 'rgba(255,255,255,0.75)' },
      border: { width: 0, style: 'none', color: 'transparent', radius: 16 },
    },
    blocked: {
      ...d().blocked,
      background: { type: 'solid', color: 'rgba(253, 236, 229, 0.6)' },
      dayNumberColor: '#e8b3a0',
      pattern: { show: true, type: 'diagonal', color: '#f4c9b9', opacity: 0.5 },
    },
  },

  // ── Cabin Glow — warm photo overlay, chunky rounded, nav pills ──
  'cabin-retreat': {
    container: {
      ...d().container,
      background: {
        type: 'image',
        color: '#fbeee3',
        imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80',
        imageSize: 'cover',
        imagePosition: 'center',
        overlay: 'rgba(255, 247, 237, 0.88)',
        opacity: 1,
      },
      border: { width: 0, style: 'none', color: 'transparent', radius: 26 },
      shadow: {
        enabled: true,
        x: 0,
        y: 12,
        blur: 40,
        spread: -8,
        color: 'rgba(217, 161, 132, 0.25)',
        inset: false,
      },
      padding: { top: 34, right: 34, bottom: 32, left: 34 },
      maxWidth: 800,
      borderRadius: 26,
    },
    header: {
      ...d().header,
      title: { ...d().header.title, alignment: 'left' },
      propertyName: {
        ...d().header.propertyName,
        color: '#d9a184',
        font: {
          ...d().header.propertyName.font,
          family: 'Outfit',
          weight: 500,
          size: 25,
          letterSpacing: 2.5,
        },
      },
      monthYear: {
        ...d().header.monthYear,
        color: '#7a5c52',
        font: { ...d().header.monthYear.font, family: 'Outfit', weight: 600, size: 40 },
      },
      navigation: {
        show: true,
        buttonBackground: 'rgba(255,255,255,0.9)',
        buttonColor: '#a97a5f',
        buttonBorder: { width: 0, style: 'none', color: 'transparent', radius: 999 },
        buttonSize: 34,
        hoverBackground: '#fdeee3',
        hoverColor: '#7a5c52',
      },
    },
    dayNames: {
      ...d().dayNames,
      background: { type: 'solid', color: 'rgba(255,255,255,0.65)' },
      color: '#a97a5f',
      font: { ...d().dayNames.font, family: 'Outfit', weight: 500, size: 12, letterSpacing: 1.5 },
      border: { width: 0, style: 'none', color: 'transparent', radius: 12 },
    },
    grid: { ...d().grid, gap: 12 },
    cell: {
      ...d().cell,
      border: { width: 0, style: 'none', color: 'transparent', radius: 22 },
      borderRadius: 22,
      background: { type: 'solid', color: 'rgba(255,255,255,0.8)' },
      dayNumber: {
        ...d().cell.dayNumber,
        font: { ...d().cell.dayNumber.font, family: 'Outfit', size: 18 },
        color: '#7a5c52',
        position: 'top-center',
      },
    },
    today: {
      ...d().today,
      background: { type: 'solid', color: '#e8b49a' },
      border: { width: 0, style: 'none', color: 'transparent', radius: 22 },
      dayNumberColor: '#ffffff',
      indicator: { show: true, type: 'dot', color: '#ffffff', size: 5 },
    },
    booked: {
      ...d().booked,
      background: { type: 'solid', color: '#e8a891' },
      dayNumberColor: '#ffffff',
      border: { width: 0, style: 'none', color: 'transparent', radius: 22 },
      icon: {
        show: true,
        type: 'icon',
        value: 'bed',
        size: 18,
        color: '#ffffff',
        position: 'center',
        opacity: 0.92,
      },
      text: { ...d().booked.text, show: false },
    },
    available: {
      ...d().available,
      background: { type: 'solid', color: 'rgba(255,255,255,0.8)' },
      border: { width: 0, style: 'none', color: 'transparent', radius: 22 },
    },
    blocked: {
      ...d().blocked,
      background: { type: 'solid', color: 'rgba(233, 205, 187, 0.55)' },
      dayNumberColor: '#d9b8a4',
      pattern: { show: true, type: 'diagonal', color: '#e8c9b5', opacity: 0.4 },
    },
  },

  // ── Dreamy Dusk — soft lilac dusk gradient, guest-name spans ──
  'velvet-guest': {
    container: {
      ...d().container,
      background: {
        type: 'gradient',
        color: '#f3e8fb',
        gradient: {
          type: 'linear',
          angle: 160,
          stops: [
            { color: '#f6ecfb', position: 0 },
            { color: '#e4d1f5', position: 55 },
            { color: '#d3b8ea', position: 100 },
          ],
        },
      },
      border: { width: 1, style: 'solid', color: 'rgba(180, 139, 217, 0.35)', radius: 26 },
      shadow: {
        enabled: true,
        x: 0,
        y: 20,
        blur: 56,
        spread: -16,
        color: 'rgba(180, 139, 217, 0.35)',
        inset: false,
      },
      padding: { top: 36, right: 34, bottom: 34, left: 34 },
      maxWidth: 800,
      borderRadius: 26,
    },
    header: {
      ...d().header,
      title: { ...d().header.title, alignment: 'center' },
      propertyName: {
        ...d().header.propertyName,
        color: '#8a5fbf',
        font: {
          ...d().header.propertyName.font,
          family: 'Manrope',
          weight: 600,
          size: 25,
          letterSpacing: 2,
        },
      },
      monthYear: {
        ...d().header.monthYear,
        color: '#5b3f8f',
        font: {
          ...d().header.monthYear.font,
          family: 'Cormorant Garamond',
          weight: 600,
          size: 40,
          lineHeight: 1.1,
        },
      },
    },
    dayNames: {
      ...d().dayNames,
      color: '#9a72c9',
      font: { ...d().dayNames.font, family: 'Manrope', weight: 600, size: 12, letterSpacing: 1.5 },
      border: { width: 0, style: 'none', color: 'transparent', radius: 0 },
    },
    grid: { ...d().grid, gap: 8 },
    cell: {
      ...d().cell,
      border: { width: 1, style: 'solid', color: 'rgba(180, 139, 217, 0.3)', radius: 18 },
      borderRadius: 18,
      background: { type: 'solid', color: 'rgba(255, 255, 255, 0.4)' },
      dayNumber: {
        ...d().cell.dayNumber,
        font: { ...d().cell.dayNumber.font, family: 'Manrope', size: 18 },
        color: '#6b4a99',
      },
    },
    today: {
      ...d().today,
      background: { type: 'solid', color: '#c9a6e8' },
      border: { width: 0, style: 'none', color: 'transparent', radius: 18 },
      dayNumberColor: '#ffffff',
      indicator: { show: true, type: 'ring', color: '#ffffff', size: 5 },
    },
    booked: {
      ...d().booked,
      background: {
        type: 'gradient',
        color: '#c9a6e8',
        gradient: {
          type: 'linear',
          angle: 150,
          stops: [
            { color: '#d6bced', position: 0 },
            { color: '#b48bd9', position: 100 },
          ],
        },
      },
      dayNumberColor: '#ffffff',
      border: { width: 0, style: 'none', color: 'transparent', radius: 18 },
      text: { ...d().booked.text, show: false },
      guestInfo: {
        ...d().booked.guestInfo,
        show: true,
        font: {
          ...d().booked.guestInfo.font,
          family: 'Manrope',
          weight: 600,
          size: 10,
          lineHeight: 1.2,
        },
        color: 'rgba(255,255,255,0.95)',
        truncate: true,
      },
    },
    available: {
      ...d().available,
      background: { type: 'solid', color: 'rgba(255, 255, 255, 0.4)' },
      dayNumberColor: '#6b4a99',
      border: { width: 1, style: 'solid', color: 'rgba(180, 139, 217, 0.3)', radius: 18 },
    },
    blocked: {
      ...d().blocked,
      background: { type: 'solid', color: 'rgba(243, 232, 251, 0.6)' },
      dayNumberColor: '#c9a6e8',
      pattern: { show: true, type: 'diagonal', color: '#b48bd9', opacity: 0.3 },
    },
  },

  // ── Rose Gold — blush plaque, rose-gold double border ──
  'gold-foil': {
    container: {
      ...d().container,
      background: { type: 'solid', color: '#fbe9ec' },
      border: { width: 4, style: 'double', color: '#e0a8a0', radius: 16 },
      shadow: {
        enabled: true,
        x: 0,
        y: 18,
        blur: 44,
        spread: -12,
        color: 'rgba(224, 168, 160, 0.35)',
        inset: false,
      },
      padding: { top: 34, right: 34, bottom: 34, left: 34 },
      maxWidth: 800,
      borderRadius: 16,
    },
    header: {
      ...d().header,
      title: { ...d().header.title, alignment: 'left' },
      propertyName: {
        ...d().header.propertyName,
        color: '#c98a80',
        font: {
          ...d().header.propertyName.font,
          family: 'Cormorant Garamond',
          weight: 600,
          size: 25,
          letterSpacing: 2.5,
        },
      },
      monthYear: {
        ...d().header.monthYear,
        color: '#8a5148',
        font: {
          ...d().header.monthYear.font,
          family: 'Cormorant Garamond',
          weight: 700,
          size: 40,
          letterSpacing: 0,
        },
      },
    },
    dayNames: {
      ...d().dayNames,
      color: '#c98a80',
      font: {
        ...d().dayNames.font,
        family: 'Cormorant Garamond',
        weight: 600,
        size: 15,
        letterSpacing: 1,
      },
      border: { width: 1, style: 'solid', color: 'rgba(224,168,160,0.3)', radius: 0 },
    },
    grid: { ...d().grid, gap: 8 },
    cell: {
      ...d().cell,
      border: { width: 1, style: 'solid', color: 'rgba(224,168,160,0.35)', radius: 10 },
      borderRadius: 10,
      background: { type: 'solid', color: '#fff7f5' },
      dayNumber: {
        ...d().cell.dayNumber,
        font: { ...d().cell.dayNumber.font, family: 'Cormorant Garamond', weight: 600, size: 30 },
        color: '#8a5148',
        position: 'top-right',
      },
    },
    today: {
      ...d().today,
      background: { type: 'solid', color: '#fff7f5' },
      border: { width: 2, style: 'solid', color: '#e0a8a0', radius: 10 },
      dayNumberColor: '#c9506d',
      indicator: { show: true, type: 'dot', color: '#e0a8a0', size: 5 },
    },
    booked: {
      ...d().booked,
      background: { type: 'solid', color: '#e0a8a0' },
      dayNumberColor: '#ffffff',
      border: { width: 1, style: 'solid', color: '#e0a8a0', radius: 10 },
      text: {
        ...d().booked.text,
        show: true,
        content: 'BOOKED',
        color: 'rgba(255,255,255,0.9)',
        font: {
          ...d().booked.text.font,
          family: 'Cormorant Garamond',
          weight: 700,
          size: 13,
          letterSpacing: 1,
        },
      },
    },
    available: {
      ...d().available,
      background: { type: 'solid', color: '#fff7f5' },
      border: { width: 1, style: 'solid', color: 'rgba(224,168,160,0.35)', radius: 10 },
    },
    blocked: {
      ...d().blocked,
      background: { type: 'solid', color: '#fdf1ee' },
      dayNumberColor: '#dcb3ac',
      border: { width: 1, style: 'solid', color: 'rgba(224,168,160,0.35)', radius: 10 },
      text: {
        ...d().blocked.text,
        show: true,
        content: 'CLOSED',
        color: '#dcb3ac',
        font: {
          ...d().blocked.text.font,
          family: 'Cormorant Garamond',
          size: 9,
          letterSpacing: 1.5,
          textTransform: 'uppercase',
        },
      },
      pattern: { show: true, type: 'diagonal', color: '#e0a8a0', opacity: 0.14 },
    },
    watermark: {
      ...d().watermark,
      show: true,
      text: 'Your brand',
      color: '#c98a80',
      opacity: 0.35,
      position: 'bottom-right',
      size: 12,
      font: {
        ...d().watermark.font,
        family: 'Cormorant Garamond',
        weight: 600,
        size: 12,
        lineHeight: 1,
        letterSpacing: 2,
        textTransform: 'uppercase',
      },
    },
  },

  // ── Ring Bloom — thin gold-blush rings on every day, elegant circles ──
  'ring-bloom': {
    container: {
      ...d().container,
      background: { type: 'solid', color: '#fffaf6' },
      border: { width: 0, style: 'none', color: 'transparent', radius: 28 },
      shadow: {
        enabled: true,
        x: 0,
        y: 18,
        blur: 48,
        spread: -16,
        color: 'rgba(201, 168, 106, 0.18)',
        inset: false,
      },
      padding: { top: 42, right: 36, bottom: 34, left: 36 },
      maxWidth: 780,
      borderRadius: 28,
    },
    header: {
      ...d().header,
      title: { ...d().header.title, alignment: 'center' },
      propertyName: {
        ...d().header.propertyName,
        color: '#c9a86a',
        font: {
          ...d().header.propertyName.font,
          family: 'Cormorant Garamond',
          weight: 600,
          size: 25,
          letterSpacing: 2.5,
          textTransform: 'uppercase',
        },
      },
      monthYear: {
        ...d().header.monthYear,
        format: 'MMMM YYYY',
        color: '#6b4a54',
        font: {
          ...d().header.monthYear.font,
          family: 'Fraunces',
          weight: 500,
          size: 40,
          lineHeight: 1.1,
        },
      },
      subtitle: {
        ...d().header.subtitle,
        show: true,
        text: 'Available dates',
        color: '#c9a8ab',
        font: {
          ...d().header.subtitle.font,
          family: 'Cormorant Garamond',
          weight: 500,
          size: 15,
          lineHeight: 1.4,
        },
      },
    },
    dayNames: {
      ...d().dayNames,
      color: '#c9a8ab',
      font: {
        ...d().dayNames.font,
        family: 'Cormorant Garamond',
        weight: 600,
        size: 15,
        letterSpacing: 1,
      },
      border: { width: 0, style: 'none', color: 'transparent', radius: 0 },
      format: 'narrow',
    },
    grid: { ...d().grid, gap: 14 },
    cell: {
      ...d().cell,
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
      border: { width: 0, style: 'none', color: 'transparent', radius: 999 },
      borderRadius: 999,
      background: { type: 'solid', color: 'transparent' },
      dayNumber: {
        ...d().cell.dayNumber,
        font: { ...d().cell.dayNumber.font, family: 'Fraunces', weight: 500, size: 19 },
        color: '#6b4a54',
        position: 'center',
      },
    },
    today: {
      ...d().today,
      background: { type: 'solid', color: 'transparent' },
      border: { width: 3, style: 'solid', color: '#c9a86a', radius: 999 },
      dayNumberColor: '#8a6a3f',
      indicator: { show: false, type: 'ring', color: '#c9a86a', size: 4 },
    },
    booked: {
      ...d().booked,
      background: { type: 'solid', color: '#e3b8ba' },
      dayNumberColor: '#ffffff',
      border: { width: 0, style: 'none', color: 'transparent', radius: 999 },
      text: { ...d().booked.text, show: false },
    },
    available: {
      ...d().available,
      background: { type: 'solid', color: 'transparent' },
      dayNumberColor: '#6b4a54',
      border: { width: 1.5, style: 'solid', color: '#e3c9cc', radius: 999 },
    },
    blocked: {
      ...d().blocked,
      background: { type: 'solid', color: 'transparent' },
      dayNumberColor: '#d9c6c8',
      border: { width: 1, style: 'dashed', color: '#e8dede', radius: 999 },
      text: { ...d().blocked.text, show: false },
      pattern: { ...d().blocked.pattern, show: false, type: 'none', color: '#e8dede', opacity: 0 },
    },
    legend: {
      ...d().legend,
      show: true,
      position: 'bottom',
      background: { type: 'solid', color: 'transparent' },
      padding: { top: 22, right: 0, bottom: 0, left: 0 },
      border: { width: 1, style: 'solid', color: '#f3e5e6', radius: 0 },
      borderRadius: 0,
      item: {
        ...d().legend.item,
        gap: 22,
        labelFont: {
          ...d().legend.item.labelFont,
          family: 'Cormorant Garamond',
          weight: 600,
          size: 14,
        },
        labelColor: '#a5808a',
        indicatorSize: 13,
        indicatorBorderRadius: 999,
      },
    },
  },

  // ── Petal Note — no cell fills anywhere, states read purely by ink color ──
  'petal-note': {
    container: {
      ...d().container,
      background: {
        type: 'gradient',
        color: '#fffaf6',
        gradient: {
          type: 'linear',
          angle: 135,
          stops: [
            { color: '#fffdfb', position: 0 },
            { color: '#fce7e0', position: 55 },
            { color: '#fffdfb', position: 100 },
          ],
        },
      },
      border: { width: 0, style: 'none', color: 'transparent', radius: 26 },
      shadow: {
        enabled: true,
        x: 0,
        y: 16,
        blur: 44,
        spread: -16,
        color: 'rgba(232, 161, 134, 0.2)',
        inset: false,
      },
      padding: { top: 40, right: 36, bottom: 34, left: 36 },
      maxWidth: 800,
      borderRadius: 26,
    },
    header: {
      ...d().header,
      title: { ...d().header.title, alignment: 'center' },
      propertyName: {
        ...d().header.propertyName,
        color: '#c96a45',
        font: {
          ...d().header.propertyName.font,
          family: 'Cormorant Garamond',
          weight: 700,
          size: 25,
          letterSpacing: 2.5,
          textTransform: 'uppercase',
        },
      },
      monthYear: {
        ...d().header.monthYear,
        format: 'MMMM YYYY',
        color: '#c25a2e',
        font: {
          ...d().header.monthYear.font,
          family: 'Fraunces',
          weight: 700,
          size: 40,
          lineHeight: 1.1,
        },
      },
    },
    dayNames: {
      ...d().dayNames,
      color: '#c96a45',
      font: {
        ...d().dayNames.font,
        family: 'Cormorant Garamond',
        weight: 700,
        size: 20,
        letterSpacing: 1.5,
      },
      background: { type: 'solid', color: 'transparent' },
      border: { width: 0, style: 'none', color: 'transparent', radius: 0 },
    },
    grid: { ...d().grid, gap: 10 },
    cell: {
      ...d().cell,
      border: { width: 0, style: 'none', color: 'transparent', radius: 0 },
      borderRadius: 0,
      background: { type: 'solid', color: 'transparent' },
      dayNumber: {
        ...d().cell.dayNumber,
        font: { ...d().cell.dayNumber.font, family: 'Cormorant Garamond', weight: 600, size: 33 },
        color: '#40312b',
        position: 'center',
      },
    },
    today: {
      ...d().today,
      background: { type: 'solid', color: 'transparent' },
      border: { width: 0, style: 'none', color: 'transparent', radius: 0 },
      dayNumberColor: '#d9622f',
      indicator: { show: true, type: 'underline', color: '#d9622f', size: 4 },
    },
    booked: {
      ...d().booked,
      background: { type: 'solid', color: 'transparent' },
      dayNumberColor: '#a84d5f',
      border: { width: 0, style: 'none', color: 'transparent', radius: 0 },
      text: { ...d().booked.text, show: false },
      pattern: { ...d().booked.pattern, show: false, type: 'none', color: '#a84d5f', opacity: 0 },
    },
    available: {
      ...d().available,
      background: { type: 'solid', color: 'transparent' },
      dayNumberColor: '#40312b',
      border: { width: 0, style: 'none', color: 'transparent', radius: 0 },
    },
    blocked: {
      ...d().blocked,
      background: { type: 'solid', color: 'transparent' },
      dayNumberColor: '#b5978a',
      border: { width: 0, style: 'none', color: 'transparent', radius: 0 },
      text: { ...d().blocked.text, show: false },
      pattern: { ...d().blocked.pattern, show: false, type: 'none', color: '#b5978a', opacity: 0 },
    },
    legend: {
      ...d().legend,
      show: true,
      position: 'bottom',
      background: { type: 'solid', color: 'transparent' },
      padding: { top: 22, right: 0, bottom: 0, left: 0 },
      border: { width: 0, style: 'none', color: 'transparent', radius: 0 },
      borderRadius: 0,
      item: {
        ...d().legend.item,
        gap: 22,
        labelFont: {
          ...d().legend.item.labelFont,
          family: 'Cormorant Garamond',
          weight: 700,
          size: 15,
        },
        labelColor: '#5c463d',
        indicatorSize: 12,
        indicatorBorderRadius: 999,
      },
    },
    watermark: {
      ...d().watermark,
      show: true,
      text: 'Your brand',
      color: '#c96a45',
      opacity: 0.32,
      position: 'bottom-right',
      size: 12,
      font: {
        ...d().watermark.font,
        family: 'Cormorant Garamond',
        weight: 600,
        size: 12,
        lineHeight: 1,
        letterSpacing: 2,
        textTransform: 'uppercase',
      },
    },
  },
};
