/** Generic form placeholders — avoid real names, contact info, or property-specific values. */
export const FORM_PLACEHOLDERS = {
  fullName: 'Ex. Jane Smith',
  towerAndUnit: 'Ex. Monaco 1234',
  phone: 'Ex. 0917 123 4567',
  email: 'janesmith@gmail.com',
  residenceName: 'Ex. Sunset Residences',
  orgDisplayName: 'My organization',
  websiteUrl: 'https://example.com',
  facebookPage: 'https://facebook.com/your-page',
  airbnbListing: 'https://airbnb.com/rooms/your-listing',
  instagramProfile: 'https://instagram.com/your-page',
  tiktokProfile: 'https://tiktok.com/@your-page',
  unitNumber: '2604',
  bookingRate: '2500',
  downPayment: '1500',
  securityDeposit: '1500',
  parkingRate: '500',
  orgDocumentsApproverEmail: 'documents@yourcompany.com',
  orgTeamEmail: 'team@yourcompany.com',
  orgParkingOwners: 'owner1@example.com, owner2@example.com',
  orgSdRefundLeadHours: '3',
  orgStaleCheckoutEmailCutoffDays: '30',
  orgDefaultParkingRate: '400',
} as const;
