#!/bin/bash
set -euo pipefail

git add -- 'supabase/migrations/20261209130000_org_team_granular_permissions.sql'
git commit -m "database(supabase): add org team granular permission migration"
echo "OK: database(supabase): add org team granular permission migration (1 files)"

git add -- 'supabase/functions/_shared/customPages.ts' 'supabase/functions/_shared/publicPageConfigs.ts'
git commit -m "api(supabase): add public property showcase endpoint"
echo "OK: api(supabase): add public property showcase endpoint (2 files)"

git add -- 'supabase/config.toml' 'supabase/functions/_shared/orgAuth.ts' 'supabase/functions/_shared/orgTeamPermissions.ts' 'supabase/functions/_shared/orgTeamService.ts' 'supabase/functions/_shared/planEntitlements.ts' 'supabase/functions/_shared/publicPropertyService.ts' 'supabase/functions/custom-pages-settings/index.ts' 'supabase/functions/org-access/index.ts' 'supabase/functions/_shared/brandColorPresets.ts' 'supabase/functions/_shared/orgLegacyPermissionExpansion.ts' 'supabase/functions/_shared/orgTeamListingAssignment.ts' 'supabase/functions/_shared/orgTeamTemplates.ts' 'supabase/functions/org-team-custom-roles/index.ts'
git commit -m "api(supabase): sync shared services and edge function updates"
echo "OK: api(supabase): sync shared services and edge function updates (13 files)"

git add -- 'ui/src/features/dashboard/team/components/OrgTeamPermissionsTab.tsx' 'ui/src/features/dashboard/team/components/PermissionsTreeView.tsx' 'ui/src/features/dashboard/team/lib/orgPermissions.ts' 'ui/src/features/dashboard/team/lib/orgLegacyPermissionExpansion.ts' 'ui/src/features/dashboard/team/lib/orgPermissionCatalog.ts' 'ui/src/features/dashboard/team/lib/orgTeamTemplates.ts'
git commit -m "ui(org): add granular property team permissions ui"
echo "OK: ui(org): add granular property team permissions ui (6 files)"

git add -- 'docs/guides/routes/property-showcase.md' 'ui/src/features/dashboard/page-editor/components/PageEditorHeader.tsx' 'ui/src/features/dashboard/page-editor/components/PageEditorPreviewPane.tsx' 'ui/src/features/dashboard/page-editor/components/property-landing/PropertyLandingEditorPanel.tsx' 'ui/src/features/dashboard/page-editor/components/property-showcase/PropertyShowcaseEditorPanel.tsx' 'ui/src/features/dashboard/page-editor/components/property-showcase/PropertyShowcasePageEditor.tsx' 'ui/src/features/dashboard/page-editor/components/shared/CopyOverrideField.tsx' 'ui/src/features/dashboard/page-editor/components/shared/ImageSlotPicker.tsx' 'ui/src/features/dashboard/page-editor/components/shared/StyleControls.tsx' 'ui/src/features/dashboard/page-editor/lib/pageEditorPreviewScroll.tsx' 'ui/src/features/dashboard/page-editor/pages/PageEditorPage.tsx' 'ui/src/features/dashboard/page-editor/stores/propertyShowcaseEditorStore.ts' 'ui/src/features/dashboard/page-editor/components/PageEditorPreviewActions.tsx' 'ui/src/features/dashboard/page-editor/components/property-showcase/ShowcaseTemplatePicker.tsx' 'ui/src/features/dashboard/page-editor/components/property-showcase/ShowcaseTemplatePreviewThumb.tsx' 'ui/src/features/dashboard/page-editor/components/shared/CtaOverrideField.tsx' 'ui/src/features/dashboard/page-editor/components/shared/HeroEyebrowField.tsx' 'ui/src/features/dashboard/page-editor/components/shared/PalettePreviewChip.tsx' 'ui/src/features/dashboard/page-editor/components/shared/ShowcaseCustomPalettePicker.tsx' 'ui/src/features/dashboard/page-editor/lib/pageEditorPublicLinks.ts' 'ui/src/features/dashboard/page-editor/lib/resolveShowcaseTemplatePickerPalette.ts' 'ui/src/features/dashboard/page-editor/lib/showcaseSectionEditorCopy.ts' 'ui/src/features/dashboard/page-editor/lib/showcaseSectionEditorFields.ts' 'ui/src/features/dashboard/page-editor/lib/showcaseTemplatePresentation.ts' 'ui/src/features/dashboard/page-editor/lib/showcaseTemplateThumbData.ts'
git commit -m "ui(ui): add property showcase page editor"
echo "OK: ui(ui): add property showcase page editor (25 files)"

git add -- 'ui/src/features/guest/marketing/showcase/components/ShowcaseCanvas.tsx' 'ui/src/features/guest/marketing/showcase/components/ShowcaseFooter.tsx' 'ui/src/features/guest/marketing/showcase/components/ShowcaseGalleryStrip.tsx' 'ui/src/features/guest/marketing/showcase/components/ShowcaseHostSection.tsx' 'ui/src/features/guest/marketing/showcase/components/ShowcaseLocationSection.tsx' 'ui/src/features/guest/marketing/showcase/components/ShowcaseMapEmbed.tsx' 'ui/src/features/guest/marketing/showcase/components/ShowcaseMotion.tsx' 'ui/src/features/guest/marketing/showcase/components/ShowcaseShell.tsx' 'ui/src/features/guest/marketing/showcase/components/ShowcaseThemeProvider.tsx' 'ui/src/features/guest/marketing/showcase/components/SmoothScrollProvider.tsx' 'ui/src/features/guest/marketing/showcase/hooks/useScrollSpy.ts' 'ui/src/features/guest/marketing/showcase/hooks/useShowcaseData.ts' 'ui/src/features/guest/marketing/showcase/lib/mapShowcaseData.ts' 'ui/src/features/guest/marketing/showcase/lib/showcaseLocation.ts' 'ui/src/features/guest/marketing/showcase/lib/showcaseScroll.ts' 'ui/src/features/guest/marketing/showcase/lib/showcaseStyleConfig.ts'
git commit -m "ui(guest-form): add property showcase public templates"
echo "OK: ui(guest-form): add property showcase public templates (16 files)"

git add -- 'ui/src/features/guest/marketing/showcase/lib/showcaseThemeTokens.ts' 'ui/src/features/guest/marketing/showcase/templates/aurora/AuroraSections.tsx' 'ui/src/features/guest/marketing/showcase/templates/aurora/AuroraTemplate.tsx' 'ui/src/features/guest/marketing/showcase/templates/editorial/EditorialSections.tsx' 'ui/src/features/guest/marketing/showcase/templates/monolith/MonolithSections.tsx' 'ui/src/features/guest/marketing/showcase/templates/registry.ts' 'ui/src/features/guest/marketing/showcase/types/showcase.ts' 'ui/src/features/guest/marketing/showcase/components/ShowcaseCtaActions.tsx' 'ui/src/features/guest/marketing/showcase/components/ShowcaseGalleryCarousel.tsx' 'ui/src/features/guest/marketing/showcase/components/ShowcaseMobileMenu.tsx' 'ui/src/features/guest/marketing/showcase/components/ShowcasePreviewMockBanner.tsx' 'ui/src/features/guest/marketing/showcase/components/ShowcaseReviewsCarousel.tsx' 'ui/src/features/guest/marketing/showcase/components/ShowcaseSectionHeading.tsx' 'ui/src/features/guest/marketing/showcase/components/ShowcaseSectionIntro.tsx' 'ui/src/features/guest/marketing/showcase/hooks/useShowcaseMediaPalette.ts' 'ui/src/features/guest/marketing/showcase/lib/showcaseBrandPalette.ts'
git commit -m "ui(guest-form): add property showcase public templates"
echo "OK: ui(guest-form): add property showcase public templates (16 files)"

git add -- 'ui/src/features/guest/marketing/showcase/lib/showcaseEditorStyleFields.ts' 'ui/src/features/guest/marketing/showcase/lib/showcaseHeaderChrome.ts' 'ui/src/features/guest/marketing/showcase/lib/showcaseHeroEyebrow.ts' 'ui/src/features/guest/marketing/showcase/lib/showcaseHeroLayout.ts' 'ui/src/features/guest/marketing/showcase/lib/showcaseHostContent.ts' 'ui/src/features/guest/marketing/showcase/lib/showcaseMediaPalette.ts' 'ui/src/features/guest/marketing/showcase/lib/showcaseMobileMenuConfig.ts' 'ui/src/features/guest/marketing/showcase/lib/showcasePalettePreview.ts' 'ui/src/features/guest/marketing/showcase/lib/showcasePaletteSurfaces.ts' 'ui/src/features/guest/marketing/showcase/lib/showcasePresetPalettes.ts' 'ui/src/features/guest/marketing/showcase/lib/showcaseSectionLayout.ts' 'ui/src/features/guest/marketing/showcase/lib/showcaseSectionMock.ts' 'ui/src/features/guest/marketing/showcase/lib/showcaseSpotlight.ts' 'ui/src/features/guest/marketing/showcase/lib/showcaseTemplateThumbSurface.tsx' 'ui/src/features/guest/marketing/showcase/lib/showcaseTypographyScale.ts' 'ui/src/features/guest/marketing/showcase/templates/atlas/AtlasSections.tsx'
git commit -m "ui(guest-form): add property showcase public templates"
echo "OK: ui(guest-form): add property showcase public templates (16 files)"

git add -- 'ui/src/features/guest/marketing/showcase/templates/atlas/AtlasTemplate.tsx' 'ui/src/features/guest/marketing/showcase/templates/aurora/AuroraParallaxSection.tsx' 'ui/src/features/guest/marketing/showcase/templates/aurora/auroraHeader.ts' 'ui/src/features/guest/marketing/showcase/templates/aurora/useAuroraHeroParallax.ts' 'ui/src/features/guest/marketing/showcase/templates/aurora/useAuroraSectionParallax.ts' 'ui/src/features/guest/marketing/showcase/templates/aurora/useShowcaseScrollProgress.ts' 'ui/src/features/guest/marketing/showcase/templates/haven/HavenSections.tsx' 'ui/src/features/guest/marketing/showcase/templates/haven/HavenTemplate.tsx' 'ui/src/features/guest/marketing/showcase/templates/monolith/monolithTypography.ts' 'ui/src/features/guest/marketing/showcase/templates/monolith/useMonolithHeroSpotlight.ts' 'ui/src/features/guest/marketing/showcase/templates/shared/ShowcaseHostSections.tsx' 'ui/src/features/guest/marketing/showcase/templates/shared/ShowcaseInfoPanels.tsx' 'ui/src/features/guest/marketing/showcase/templates/shared/showcaseKinetic.tsx' 'ui/src/features/guest/marketing/showcase/templates/verso/VersoSections.tsx' 'ui/src/features/guest/marketing/showcase/templates/verso/VersoTemplate.tsx' 'ui/src/features/guest/marketing/showcase/templates/verso/versoTypography.ts'
git commit -m "ui(guest-form): add property showcase public templates"
echo "OK: ui(guest-form): add property showcase public templates (16 files)"

git add -- 'ui/src/features/guest/marketing/properties/lib/mapPublicPropertyDetail.ts' 'ui/src/features/guest/marketing/properties/lib/propertyMapEmbed.ts' 'ui/src/features/guest/marketing/properties/types/publicProperty.ts'
git commit -m "ui(guest-form): refine guest marketing routes and property pages"
echo "OK: ui(guest-form): refine guest marketing routes and property pages (3 files)"

git add -- 'ui/src/features/dashboard/custom-pages/components/PublicPageCard.tsx' 'ui/src/features/dashboard/custom-pages/lib/publicPageLastEdited.ts' 'ui/src/features/dashboard/custom-pages/pages/CustomPagesPage.tsx' 'ui/src/features/dashboard/marketing/components/calendar-builder/components/CalendarBuilder.tsx' 'ui/src/features/dashboard/marketing/components/design-editor/PolotnoDesignStudio.tsx' 'ui/src/features/dashboard/marketing/components/shared/MarketingAiGeneratePanel.tsx' 'ui/src/features/dashboard/marketing/components/video-editor/VideoEditor.tsx' 'ui/src/features/dashboard/marketing/lib/calendarAiGenerateOptions.ts' 'ui/src/features/dashboard/marketing/lib/designAiGenerateOptions.ts' 'ui/src/features/dashboard/org/components/property-settings/PropertyMediaUpload.tsx' 'ui/src/features/dashboard/org/components/property-settings/PropertyProfileSettingsSections.tsx' 'ui/src/features/dashboard/org/components/settings/BrandColorField.tsx' 'ui/src/features/dashboard/plans/components/PlanFeatureMatrix.tsx' 'ui/src/features/dashboard/plans/lib/planPresentation.ts' 'ui/src/features/dashboard/property/lib/propertyGuestPublicPages.ts' 'ui/src/features/dashboard/team/components/CustomRoleFormDialog.tsx' 'ui/src/features/dashboard/team/components/CustomRolesSection.tsx' 'ui/src/features/dashboard/team/components/OrgInviteMemberDialog.tsx' 'ui/src/features/dashboard/team/components/OrgRoleBadge.tsx'
git commit -m "ui(ui): sync batch 1 dashboard shell components and styles"
echo "OK: ui(ui): sync batch 1 dashboard shell components and styles (19 files)"

git add -- 'ui/src/features/dashboard/team/components/OrgTeamMembersTab.tsx' 'ui/src/features/dashboard/team/components/RoleSelectOptions.tsx' 'ui/src/features/dashboard/team/hooks/useOrgTeam.ts' 'ui/src/features/dashboard/team/lib/orgTeamConstants.ts' 'ui/src/features/dashboard/team/lib/orgTeamRoles.ts' 'ui/src/features/dashboard/team/lib/teamRoleHelpers.ts' 'ui/src/features/dashboard/team/lib/teamScopeConfig.ts' 'ui/src/features/dashboard/team/pages/OrgTeamPage.tsx' 'ui/src/features/dashboard/team/types/orgTeam.ts' 'ui/src/index.css' 'ui/tailwind.config.js' 'ui/src/features/dashboard/marketing/hooks/useMarketingMediaAccent.ts' 'ui/src/features/dashboard/marketing/lib/marketingAiPhotoPalette.ts' 'ui/src/features/dashboard/team/components/OrgListingAssignmentPicker.tsx' 'ui/src/features/dashboard/team/components/OrgManageMemberDialog.tsx' 'ui/src/lib/theme/brandColorPresets.ts' 'ui/src/lib/theme/hsvColor.ts' 'ui/src/lib/theme/photoBrandColor.ts'
git commit -m "ui(ui): sync batch 2 dashboard shell components and styles"
echo "OK: ui(ui): sync batch 2 dashboard shell components and styles (18 files)"

git add -- 'docs/PROJECT.md' 'docs/architecture/plans-feature-matrix.md' 'docs/guides/routes/org/plans.md' 'docs/guides/routes/org/property/marketing.md' 'docs/guides/routes/org/property/public-pages.md' 'docs/guides/routes/org/property/settings.md' 'docs/guides/routes/org/property/team.md' 'docs/guides/routes/org/team.md'
git commit -m "docs(docs): sync architecture route guides and shipped workflow docs"
echo "OK: docs(docs): sync architecture route guides and shipped workflow docs (8 files)"

git add -- 'package.json'
git commit -m "chore(deps): update root and ui package locks"
echo "OK: chore(deps): update root and ui package locks (1 files)"

git add -- 'scripts/README.md' 'scripts/dev/batch-commit-plan-25.mjs' 'scripts/dev/batch-commit-run.sh' 'scripts/dev/batch-commit-wip-filter.mjs'
git commit -m "chore(*): add batch commit dev utilities and update scripts readme"
echo "OK: chore(*): add batch commit dev utilities and update scripts readme (4 files)"

echo "DONE 15 commits"